<div id="sidebar">

    <div class="actions clearfix">
        <a class="bigbutton muted" href="./">Back to all Files</a>
    </div>

    <hr/>

    <div class="pod">
        <h2>Manage file</h2>

        <p>
            <a id="fileReplaceOpenButton" class="button" href="#">Upload a new
                version</a>
            <a class="button warning" href="#">Delete</a>
        </p>
    </div>

    <div class="pod">
        <h2>Versions</h2>
        <ul class="versions clearfix">
            <li class="current">
                <a href="#">
                    <h3>7 mins ago</h3> <em class="published">(Published)</em>

                    <p>by Sandrine Pichet</p>
                </a>
            </li>
            <li>
                <a href="#">
                    <h3>34 mins ago</h3>

                    <p>by Herman Razubol</p>
                </a>
            </li>
            <li>
                <a href="#">
                    <h3>24 Jan 2008 at 10:48</h3>

                    <p>by Sandrine Pichet</p>
                </a>
            </li>
            <li>
                <a href="#">
                    <h3>24 Jan 2008 at 9:05</h3>

                    <p>by Sandrine Pichet</p>
                </a>
            </li>
            <li>
                <a href="#">
                    <h3>3 Dec 2007 at 11:52</h3>

                    <p>by Herman Razubol</p>
                </a>
            </li>
            <li class="viewall">
                <a href="#">
                    <h3>View all...</h3>
                </a>
            </li>
        </ul>
    </div>
</div>