<?php echo $this->addiScript; ?>
<div class="dialogConvertCls"></div>

<div id="fileEdit"></div>
<div id="filesBrowse">
    <div xmlns="http://www.w3.org/1999/xhtml" class="sydney_editor_toolbar">
        <form>
            <div>
                <label>View</label>

                <div class="buttons">
                    <a id="thumbviewb" class="active" title="Thumbnails"
                       style="background-image: url(<?php echo $this->cdnurl; ?>/sydneyassets/images/ui/toolbar/thumbs.png);"
                       href="#">Cards</a>
                    <a id="listviewb" title="List"
                       style="background-image: url(<?php echo $this->cdnurl; ?>/sydneyassets/images/ui/toolbar/list.png);"
                       href="#"><?= Sydney_Tools_Localization::_('Table') ?></a>
                </div>
            </div>
            <div>
                <label
                    for="sortBy1"><?= Sydney_Tools_Localization::_('Sort by') ?></label>
                <select id="sortBy1">
                    <option><?= Sydney_Tools_Localization::_('Last modified') ?></option>
                    <option><?= Sydney_Tools_Localization::_('Name') ?></option>
                </select>

                <a id="descbut" title="Reverse sort order" href="#">
                    <img height="20" width="12"
                         src="<?php echo $this->cdnurl; ?>/sydneyassets/images/ui/toolbar/sort_arrows.png"
                         alt="<?= Sydney_Tools_Localization::_('Reverse sort order') ?>"/>
                </a>
            </div>
            <div class="ui-toolbar-item-filter">
                <label><?= Sydney_Tools_Localization::_('Filter') ?></label>
                <select id="sortBy2">
                    <option value="-">-</option>
                </select>
                <a class="ui-toolbar-smartquery-toggle fladvfilter"
                   title="Advanced filter" href="#"
                   style="text-indent:0px;background:none;">
                    <img
                        src="<?php echo $this->cdnurl; ?>/sydneyassets/images/ui/toolbar/smartquery.png"
                        border="0"/>
                </a>

                <div class="advfilfiltersbox"></div>
            </div>
            <div class="ui-toolbar-item-filter">
                <label><?= Sydney_Tools_Localization::_('Folder view') ?></label>
                <input type="checkbox" name="folderviewname" id="folderview"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <input type="button" value="New folder" id="createfoldbtn"
                       style="font-size:.7em;font-weight:normal;padding:3px;"/>
            </div>
        </form>
        <br>

        <div
            id="butselection"><?= Sydney_Tools_Localization::_('selection') ?></div>
    </div>

    <ul xmlns="http://www.w3.org/1999/xhtml" class="sydney_editor_paging">
        <ul>
            <li><a href="#"
                   id="prevbut-header"><?= Sydney_Tools_Localization::_('Previous items') ?></a><a
                    id="prevbuto-header"><?= Sydney_Tools_Localization::_('Previous items') ?></a>
            </li>
            <li><a href="#"
                   id="nextbut-header"><?= Sydney_Tools_Localization::_('Next items') ?></a><a
                    id="nextbuto-header"><?= Sydney_Tools_Localization::_('Next items') ?></a>
            </li>
        </ul>

        <div id="pagination-header">
        </div>
    </ul>

    <div id="filelisting" class="filelistscroll"></div>

    <?php if ($this->embed): ?>
        <ul xmlns="http://www.w3.org/1999/xhtml" class="sydney_editor_paging">
            <ul>
                <li><a href="#"
                       id="prevbut-footer"><?= Sydney_Tools_Localization::_('Previous items') ?></a><a
                        id="prevbuto-footer"><?= Sydney_Tools_Localization::_('Previous items') ?></a>
                </li>
                <li><a href="#"
                       id="nextbut-footer"><?= Sydney_Tools_Localization::_('Next items') ?></a><a
                        id="nextbuto-footer"><?= Sydney_Tools_Localization::_('Next items') ?></a>
                </li>
            </ul>
            <div id="pagination-footer"></div>
        </ul>
    <?php endif; ?>
</div>


