<?php
/**
 * File generated by the Sydney_Admin_Generator v2.0
 */

/**
 * Mapping of the Pagdivtypes table in an object
 * @package Admindb
 * @subpackage ModelGenerated
 */
class Pagdivtypes extends PagdivtypesOp
{
    protected $_schema = 'sydney';
    protected $_name = 'pagdivtypes';
    protected $_dependentTables = array('Pagdivs');
    protected $_referenceMap = array(
        'Safmodules' => array(
            'columns'       => 'safmodules_id',
            'refTableClass' => 'Safmodules',
            'refColumns'    => 'id'
        ),
    );
    protected $_primary = 'id';

    public $fieldsNames = array(
        'id', // bigint()
        'safmodules_id', // bigint()
        'label', // varchar(45)
        'desc', // varchar(255)
        'online', // tinyint()
        'helper', // varchar(100)
        'helperadmin', // varchar(150)
        'code', // varchar(45)
        'developeronly', // tinyint()
    );

    protected $_metadata = array(
        'id'            => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "pagdivtypes",
            'COLUMN_NAME'      => "id",
            'COLUMN_POSITION'  => 1,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => true,
            'PRIMARY_POSITION' => 1,
            'IDENTITY'         => true,
        ),
        'safmodules_id' => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "pagdivtypes",
            'COLUMN_NAME'      => "safmodules_id",
            'COLUMN_POSITION'  => 2,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'label'         => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "pagdivtypes",
            'COLUMN_NAME'      => "label",
            'COLUMN_POSITION'  => 3,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => true,
            'LENGTH'           => "45",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'desc'          => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "pagdivtypes",
            'COLUMN_NAME'      => "desc",
            'COLUMN_POSITION'  => 4,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => true,
            'LENGTH'           => "255",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'online'        => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "pagdivtypes",
            'COLUMN_NAME'      => "online",
            'COLUMN_POSITION'  => 5,
            'DATA_TYPE'        => "tinyint",
            'DEFAULT'          => "1",
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'helper'        => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "pagdivtypes",
            'COLUMN_NAME'      => "helper",
            'COLUMN_POSITION'  => 6,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => true,
            'LENGTH'           => "100",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'helperadmin'   => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "pagdivtypes",
            'COLUMN_NAME'      => "helperadmin",
            'COLUMN_POSITION'  => 7,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "150",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'code'          => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "pagdivtypes",
            'COLUMN_NAME'      => "code",
            'COLUMN_POSITION'  => 8,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => true,
            'LENGTH'           => "45",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'developeronly' => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "pagdivtypes",
            'COLUMN_NAME'      => "developeronly",
            'COLUMN_POSITION'  => 9,
            'DATA_TYPE'        => "tinyint",
            'DEFAULT'          => "0",
            'NULLABLE'         => true,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
    );

    public function __construct($id = 0)
    {
        $this->_schema = Sydney_Tools_Sydneyglobals::getConf()->db->params->dbname;
        parent::__construct($id);
    }

}
