<?php
/**
 * File generated by the Sydney_Admin_Generator v2.0
 */

/**
 * Mapping of the Pagmenus table in an object
 * @package Admindb
 * @subpackage ModelGenerated
 */
class Pagmenus extends PagmenusOp
{
    protected $_schema = 'sydney';
    protected $_name = 'pagmenus';
    protected $_dependentTables = array(
        'PagmenusSafinstances',
        'PagstructurePagmenus'
    );
    protected $_primary = 'id';

    public $fieldsNames = array(
        'id', // bigint()
        'label', // varchar(45)
        'desc', // varchar(255)
        'active', // tinyint()
    );

    protected $_metadata = array(
        'id'     => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "pagmenus",
            'COLUMN_NAME'      => "id",
            'COLUMN_POSITION'  => 1,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => true,
            'PRIMARY_POSITION' => 1,
            'IDENTITY'         => true,
        ),
        'label'  => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "pagmenus",
            'COLUMN_NAME'      => "label",
            'COLUMN_POSITION'  => 2,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => true,
            'LENGTH'           => "45",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'desc'   => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "pagmenus",
            'COLUMN_NAME'      => "desc",
            'COLUMN_POSITION'  => 3,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => true,
            'LENGTH'           => "255",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'active' => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "pagmenus",
            'COLUMN_NAME'      => "active",
            'COLUMN_POSITION'  => 4,
            'DATA_TYPE'        => "tinyint",
            'DEFAULT'          => "1",
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
    );

    public function __construct($id = 0)
    {
        $this->_schema = Sydney_Tools_Sydneyglobals::getConf()->db->params->dbname;
        parent::__construct($id);
    }

}
