<?php
/**
 * File generated by the Sydney_Admin_Generator v2.0
 */

/**
 * Mapping of the PagmenusSafinstances table in an object
 * @package Admindb
 * @subpackage ModelGenerated
 */
class PagmenusSafinstances extends PagmenusSafinstancesOp
{
    protected $_schema = 'sydney';
    protected $_name = 'pagmenus_safinstances';
    protected $_referenceMap = array(
        'Pagmenus'     => array(
            'columns'       => 'pagmenus_id',
            'refTableClass' => 'Pagmenus',
            'refColumns'    => 'id'
        ),
        'Safinstances' => array(
            'columns'       => 'safinstances_id',
            'refTableClass' => 'Safinstances',
            'refColumns'    => 'id'
        ),
    );
    protected $_primary = 'id';

    public $fieldsNames = array(
        'pagmenus_id', // bigint()
        'safinstances_id', // bigint()
        'id', // bigint()
    );

    protected $_metadata = array(
        'pagmenus_id'     => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "pagmenus_safinstances",
            'COLUMN_NAME'      => "pagmenus_id",
            'COLUMN_POSITION'  => 1,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'safinstances_id' => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "pagmenus_safinstances",
            'COLUMN_NAME'      => "safinstances_id",
            'COLUMN_POSITION'  => 2,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'id'              => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "pagmenus_safinstances",
            'COLUMN_NAME'      => "id",
            'COLUMN_POSITION'  => 3,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => true,
            'PRIMARY_POSITION' => 1,
            'IDENTITY'         => true,
        ),
    );

    /**
     * Returns the list of IDs linked to a "Pagmenus"
     *
     * @param Int $id ID of the safinstances
     * @return Array list of IDs
     */
    public function getPagmenusLinkedTo($id)
    {
        if (preg_match("/[0-9]{1,9}/", $id)) {
            $toreturn = array();
            $rows = $this->fetchAll($this->select()->where('safinstances_id = ?', $id));
            foreach ($rows->toArray() as $v) {
                $toreturn[] = $v['pagmenus_id'];
            }

            return $toreturn;
        } else {
            return array();
        }
    }

    /**
     * Sets the data linked to an id in the "Pagmenus" table
     *
     * @param Int $id ID of the safinstances
     * @param Array list of IDs
     * @return Boolean true if success and false if there were an error
     */
    public function setPagmenusLinkedTo($id, array $data)
    {
        if (preg_match("/[0-9]{1,9}/", $id) && is_array($data)) {
            $where = $this->getAdapter()->quoteInto('pagmenus_id = ?', $id);
            $this->delete($where);
            foreach ($data as $v) {
                $this->insert(array(
                    'pagmenus_id'     => $id,
                    'safinstances_id' => $v
                ));
            }
        } else {
            return false;
        }
    }

    /**
     * Returns the list of IDs linked to a "Safinstances"
     *
     * @param Int $id ID of the pagmenus
     * @return Array list of IDs
     */
    public function getSafinstancesLinkedTo($id)
    {
        if (preg_match("/[0-9]{1,9}/", $id)) {
            $toreturn = array();
            $rows = $this->fetchAll($this->select()->where('pagmenus_id = ?', $id));
            foreach ($rows->toArray() as $v) {
                $toreturn[] = $v['safinstances_id'];
            }

            return $toreturn;
        } else {
            return array();
        }
    }

    /**
     * Sets the data linked to an id in the "Safinstances" table
     *
     * @param Int $id ID of the pagmenus
     * @param Array list of IDs
     * @return Boolean true if success and false if there were an error
     */
    public function setSafinstancesLinkedTo($id, array $data)
    {
        if (preg_match("/[0-9]{1,9}/", $id) && is_array($data)) {
            $where = $this->getAdapter()->quoteInto('safinstances_id = ?', $id);
            $this->delete($where);
            foreach ($data as $v) {
                $this->insert(array(
                    'safinstances_id' => $id,
                    'pagmenus_id'     => $v
                ));
            }
        } else {
            return false;
        }
    }

    public function __construct($id = 0)
    {
        $this->_schema = Sydney_Tools_Sydneyglobals::getConf()->db->params->dbname;
        parent::__construct($id);
    }

}
