<?php
/**
 * File generated by the Sydney_Admin_Generator v2.0
 */

/**
 * Mapping of the PagstructurePagdivs table in an object
 * @package Admindb
 * @subpackage ModelGenerated
 */
class PagstructurePagdivs extends PagstructurePagdivsOp
{
    protected $_schema = 'sydney';
    protected $_name = 'pagstructure_pagdivs';
    protected $_referenceMap = array(
        'Pagstructure' => array(
            'columns'       => 'pagstructure_id',
            'refTableClass' => 'Pagstructure',
            'refColumns'    => 'id'
        ),
        'Pagdivs'      => array(
            'columns'       => 'pagdivs_id',
            'refTableClass' => 'Pagdivs',
            'refColumns'    => 'id'
        ),
    );
    protected $_primary = 'id';

    public $fieldsNames = array(
        'pagstructure_id', // bigint()
        'pagdivs_id', // bigint()
        'id', // bigint()
        'order', // int()
        'zone', // varchar(60)
    );

    protected $_metadata = array(
        'pagstructure_id' => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "pagstructure_pagdivs",
            'COLUMN_NAME'      => "pagstructure_id",
            'COLUMN_POSITION'  => 1,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'pagdivs_id'      => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "pagstructure_pagdivs",
            'COLUMN_NAME'      => "pagdivs_id",
            'COLUMN_POSITION'  => 2,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'id'              => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "pagstructure_pagdivs",
            'COLUMN_NAME'      => "id",
            'COLUMN_POSITION'  => 3,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => true,
            'PRIMARY_POSITION' => 1,
            'IDENTITY'         => true,
        ),
        'order'           => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "pagstructure_pagdivs",
            'COLUMN_NAME'      => "order",
            'COLUMN_POSITION'  => 4,
            'DATA_TYPE'        => "int",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'zone'            => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "pagstructure_pagdivs",
            'COLUMN_NAME'      => "zone",
            'COLUMN_POSITION'  => 5,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => true,
            'LENGTH'           => "60",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
    );

    /**
     * Returns the list of IDs linked to a "Pagstructure"
     *
     * @param Int $id ID of the pagdivs
     * @return Array list of IDs
     */
    public function getPagstructureLinkedTo($id)
    {
        if (preg_match("/[0-9]{1,9}/", $id)) {
            $toreturn = array();
            $rows = $this->fetchAll($this->select()->where('pagdivs_id = ?', $id));
            foreach ($rows->toArray() as $v) {
                $toreturn[] = $v['pagstructure_id'];
            }

            return $toreturn;
        } else {
            return array();
        }
    }

    /**
     * Sets the data linked to an id in the "Pagstructure" table
     *
     * @param Int $id ID of the pagdivs
     * @param Array list of IDs
     * @return Boolean true if success and false if there were an error
     */
    public function setPagstructureLinkedTo($id, array $data)
    {
        if (preg_match("/[0-9]{1,9}/", $id) && is_array($data)) {
            $where = $this->getAdapter()->quoteInto('pagstructure_id = ?', $id);
            $this->delete($where);
            foreach ($data as $v) {
                $this->insert(array(
                    'pagstructure_id' => $id,
                    'pagdivs_id'      => $v
                ));
            }
        } else {
            return false;
        }
    }

    /**
     * Returns the list of IDs linked to a "Pagdivs"
     *
     * @param Int $id ID of the pagstructure
     * @return Array list of IDs
     */
    public function getPagdivsLinkedTo($id)
    {
        if (preg_match("/[0-9]{1,9}/", $id)) {
            $toreturn = array();
            $rows = $this->fetchAll($this->select()->where('pagstructure_id = ?', $id));
            foreach ($rows->toArray() as $v) {
                $toreturn[] = $v['pagdivs_id'];
            }

            return $toreturn;
        } else {
            return array();
        }
    }

    /**
     * Sets the data linked to an id in the "Pagdivs" table
     *
     * @param Int $id ID of the pagstructure
     * @param Array list of IDs
     * @return Boolean true if success and false if there were an error
     */
    public function setPagdivsLinkedTo($id, array $data)
    {
        if (preg_match("/[0-9]{1,9}/", $id) && is_array($data)) {
            $where = $this->getAdapter()->quoteInto('pagdivs_id = ?', $id);
            $this->delete($where);
            foreach ($data as $v) {
                $this->insert(array(
                    'pagdivs_id'      => $id,
                    'pagstructure_id' => $v
                ));
            }
        } else {
            return false;
        }
    }

    public function __construct($id = 0)
    {
        $this->_schema = Sydney_Tools_Sydneyglobals::getConf()->db->params->dbname;
        parent::__construct($id);
    }

}
