<?php
/**
 * File generated by the Sydney_Admin_Generator
 */

/**
 * Form to manage the data from the pagdivtypes table
 * @package Admindb
 * @subpackage FormmodelGenerated
 */
class PagdivtypesForm extends Sydney_Form
{
    public function __construct($options = null)
    {
        parent :: __construct($options);
        $this->setAttrib('accept-charset', 'UTF-8');
        $this->setName('pagdivtypes');

        $id = new Zend_Form_Element_Hidden('id');

        $hash = new Zend_Form_Element_Hash('no_csrf_foo', array('salt' => '4s564evzaSD64sf'));

        $submit = new Zend_Form_Element_Submit('submit');
        $submit->setAttrib('id', 'submitbutton');

        $safModulesId = new Zend_Form_Element_Select('safmodules_id');
        $options = new Safmodules();
        $safModulesId->addMultiOption('', '----------');
        foreach ($options->fetchAlltoFlatArray() as $k => $v) {
            $safModulesId->addMultiOption($k, $v['mlabel']);
        }

        $safModulesId->setLabel('safmodules_id');

        $label = new Zend_Form_Element_Text('label');
        $label->setLabel('label');

        $desc = new Zend_Form_Element_Textarea('desc');
        $desc->setLabel('desc');

        $online = new Zend_Form_Element_Checkbox('online');
        $online->setLabel('online');

        $helper = new Zend_Form_Element_Text('helper');
        $helper->setLabel('helper');

        $helperAdmin = new Zend_Form_Element_Textarea('helperadmin');
        $helperAdmin->setLabel('helperadmin');

        $code = new Zend_Form_Element_Text('code');
        $code->setLabel('code');

        $developerOnly = new Zend_Form_Element_Text('developeronly');
        $developerOnly->setLabel('developeronly');

        $this->addElements(array(
            $id,
            $hash,
            $safModulesId,
            $label,
            $desc,
            $online,
            $helper,
            $helperAdmin,
            $code,
            $developerOnly
        ));
        $this->addElements(array($submit));
    }

}
