<?php
/**
 * File generated by the Sydney_Admin_Generator
 */

/**
 * Form to manage the data from the pagmenus table
 * @package Admindb
 * @subpackage FormmodelGenerated
 */
class PagmenusForm extends Sydney_Form
{
    public function __construct($options = null)
    {
        parent :: __construct($options);
        $this->setAttrib('accept-charset', 'UTF-8');
        $this->setName('pagmenus');

        $id = new Zend_Form_Element_Hidden('id');

        $hash = new Zend_Form_Element_Hash('no_csrf_foo', array('salt' => '4s564evzaSD64sf'));

        $submit = new Zend_Form_Element_Submit('submit');
        $submit->setAttrib('id', 'submitbutton');

        $label = new Zend_Form_Element_Text('label');
        $label->setLabel('label');

        $desc = new Zend_Form_Element_Textarea('desc');
        $desc->setLabel('desc');

        $active = new Zend_Form_Element_Checkbox('active');
        $active->setLabel('active');

        $pagMenusSafinstances = new SafinstanceslistForm('PagmenusSafinstances');
        $pagMenusSafinstances->setLabel('PagmenusSafinstances');
        $pagStructurePagMenus = new PagstructurelistForm('PagstructurePagmenus');
        $pagStructurePagMenus->setLabel('PagstructurePagmenus');

        $this->addElements(array(
            $id,
            $hash,
            $label,
            $desc,
            $active,
            $pagMenusSafinstances,
            $pagStructurePagMenus
        ));
        $this->addElements(array($submit));
    }

}
