<?php
/**
 * File generated by the Sydney_Admin_Generator
 */

/**
 * Form to manage the data from the pagstats table
 * @package Admindb
 * @subpackage FormmodelGenerated
 */
class PagstatsForm extends Sydney_Form
{
    public function __construct($options = null)
    {
        parent :: __construct($options);
        $this->setAttrib('accept-charset', 'UTF-8');
        $this->setName('pagstats');

        $id = new Zend_Form_Element_Hidden('id');

        $hash = new Zend_Form_Element_Hash('no_csrf_foo', array('salt' => '4s564evzaSD64sf'));

        $submit = new Zend_Form_Element_Submit('submit');
        $submit->setAttrib('id', 'submitbutton');

        $pagStructureId = new Zend_Form_Element_Select('pagstructure_id');
        $options = new Pagstructure();
        $pagStructureId->addMultiOption('', '----------');
        foreach ($options->fetchAlltoFlatArray() as $k => $v) {
            $pagStructureId->addMultiOption($k, $v['mlabel']);
        }

        $pagStructureId->setLabel('pagstructure_id');

        $views = new Zend_Form_Element_Text('views');
        $views->setLabel('views');

        $unique = new Zend_Form_Element_Text('unique');
        $unique->setLabel('unique');

        $timeOnPage = new Zend_Form_Element_Text('timeonpage');
        $timeOnPage->setLabel('timeonpage');

        $bounces = new Zend_Form_Element_Text('bounces');
        $bounces->setLabel('bounces');

        $exits = new Zend_Form_Element_Text('exits');
        $exits->setLabel('exits');

        $this->addElements(array(
            $id,
            $hash,
            $pagStructureId,
            $views,
            $unique,
            $timeOnPage,
            $bounces,
            $exits
        ));
        $this->addElements(array($submit));
    }

}
