<?php
/**
 * File generated by the Sydney_Admin_Generator
 */

/**
 * Form to manage the data from the pagstructure table
 * @package Admindb
 * @subpackage FormmodelGenerated
 */
class PagstructureForm extends Sydney_Form
{
    public function __construct($options = null)
    {
        parent :: __construct($options);
        $this->setAttrib('accept-charset', 'UTF-8');
        $this->setName('pagstructure');

        $id = new Zend_Form_Element_Hidden('id');

        $hash = new Zend_Form_Element_Hash('no_csrf_foo', array('salt' => '4s564evzaSD64sf'));

        $submit = new Zend_Form_Element_Submit('submit');
        $submit->setAttrib('id', 'submitbutton');

        $label = new Zend_Form_Element_Textarea('label');
        $label->setLabel('label');

        $htmlTitle = new Zend_Form_Element_Textarea('htmltitle');
        $htmlTitle->setLabel('htmltitle');

        $url = new Zend_Form_Element_Textarea('url');
        $url->setLabel('url');

        $metaDesc = new Zend_Form_Element_Textarea('metadesc');
        $metaDesc->setLabel('metadesc');

        $metaKeywords = new Zend_Form_Element_Textarea('metakeywords');
        $metaKeywords->setLabel('metakeywords');

        $parentId = new Zend_Form_Element_Select('parent_id');
        $options = new Pagstructure();
        $parentId->addMultiOption('', '----------');
        foreach ($options->fetchAlltoFlatArray() as $k => $v) {
            $parentId->addMultiOption($k, $v['mlabel']);
        }

        $parentId->setLabel('parent_id');

        $safinstancesId = new Zend_Form_Element_Select('safinstances_id');
        $options = new Safinstances();
        $safinstancesId->addMultiOption('', '----------');
        foreach ($options->fetchAlltoFlatArray() as $k => $v) {
            $safinstancesId->addMultiOption($k, $v['mlabel']);
        }

        $safinstancesId->setLabel('safinstances_id');

        $isHome = new Zend_Form_Element_Text('ishome');
        $isHome->setLabel('ishome');

        $status = new Zend_Form_Element_Text('status');
        $status->setLabel('status');

        $pagOrder = new Zend_Form_Element_Text('pagorder');
        $pagOrder->setLabel('pagorder');

        $dateCreated = new Zend_Form_Element_Text('datecreated');
        $dateCreated->setLabel('datecreated');

        $dateModified = new Zend_Form_Element_Text('datemodified');
        $dateModified->setLabel('datemodified');

        $dateLastUpdateContent = new Zend_Form_Element_Text('date_lastupdate_content');
        $dateLastUpdateContent->setLabel('date_lastupdate_content');

        $whoModified = new Zend_Form_Element_Text('who_modified');
        $whoModified->setLabel('who_modified');

        $whoLastUpdateContent = new Zend_Form_Element_Text('who_lastupdate_content');
        $whoLastUpdateContent->setLabel('who_lastupdate_content');

        $isCachable = new Zend_Form_Element_Text('iscachable');
        $isCachable->setLabel('iscachable');

        $cacheTime = new Zend_Form_Element_Text('cachetime');
        $cacheTime->setLabel('cachetime');

        $hits = new Zend_Form_Element_Text('hits');
        $hits->setLabel('hits');

        $redirectToId = new Zend_Form_Element_Text('redirecttoid');
        $redirectToId->setLabel('redirecttoid');

        $usersGroupsId = new Zend_Form_Element_Select('usersgroups_id');
        $options = new Usersgroups();
        $usersGroupsId->addMultiOption('', '----------');
        foreach ($options->fetchAlltoFlatArray() as $k => $v) {
            $usersGroupsId->addMultiOption($k, $v['mlabel']);
        }

        $usersGroupsId->setLabel('usersgroups_id');

        $isDeleted = new Zend_Form_Element_Text('isDeleted');
        $isDeleted->setLabel('isDeleted');

        $shortDesc = new Zend_Form_Element_Textarea('shortdesc');
        $shortDesc->setLabel('shortdesc');

        $colorCode = new Zend_Form_Element_Text('colorcode');
        $colorCode->setLabel('colorcode');

        $layout = new Zend_Form_Element_Text('layout');
        $layout->setLabel('layout');

        $pagStructurePagDivs = new PagdivslistForm('PagstructurePagdivs');
        $pagStructurePagDivs->setLabel('PagstructurePagdivs');
        $pagStructurePagMenus = new PagmenuslistForm('PagstructurePagmenus');
        $pagStructurePagMenus->setLabel('PagstructurePagmenus');

        $this->addElements(array(
            $id,
            $hash,
            $label,
            $htmlTitle,
            $url,
            $metaDesc,
            $metaKeywords,
            $parentId,
            $safinstancesId,
            $isHome,
            $status,
            $pagOrder,
            $dateCreated,
            $dateModified,
            $dateLastUpdateContent,
            $whoModified,
            $whoLastUpdateContent,
            $isCachable,
            $cacheTime,
            $hits,
            $redirectToId,
            $usersGroupsId,
            $isDeleted,
            $shortDesc,
            $colorCode,
            $layout,
            $pagStructurePagDivs,
            $pagStructurePagMenus
        ));
        $this->addElements(array($submit));
    }

}
