<div id="sidebar">
    <div class="actions clearfix">
        <a href="/adminpages/" class="bigbutton muted" style="font-size:90%;">
            Back to Structure & Pages</a>
    </div>

    <div class="pod"><h2>Recycle Bin</h2>

        <div>
            <a id="emptyRecyclebin" href="/adminpages/index/index/"
               class="button warning">Empty Recycle Bin !</a>
        </div>
    </div>

</div>
