<?php
/**
 * File generated by the Sydney_Admin_Generator on the Mar 25, 2010 2:17:05 PM by arnaud@antidot.ca
 */

/**
 * Form to manage the data from the users table
 * @package Admindb
 * @subpackage FormmodelGenerated
 */
class UsersWebsitePermisionsForm extends Sydney_Form
{
    public function __construct($options = null)
    {
        parent :: __construct($options);
        $this->setAttrib('accept-charset', 'UTF-8');
        $this->setName('users');

        $id = new Zend_Form_Element_Hidden('id');
        $submit = new Zend_Form_Element_Submit('submit');
        $submit->setAttrib('id', 'submitbutton');

        $safinstancesId = new Zend_Form_Element_Select('saf_id');
        $options = new Safinstances();
        $safinstancesId->addMultiOption('', '----------');
        foreach ($options->fetchAlltoFlatArray() as $k => $v) {
            $safinstancesId->addMultiOption($k, $v['mlabel']);
        }
        $safinstancesId->setLabel('Main website');
        $safinstancesId->setRequired(true);

        $safinstancesUsers = new SafinstanceslistForm('SafinstancesUsers');
        $safinstancesUsers->setLabel('Additional website(s)');

        $this->addElements(array(
            $id,
            $safinstancesId,
            $safinstancesUsers,
            $submit
        ));
    }

}
