<?php
/**
 * File generated by the Sydney_Admin_Generator
 */

/**
 * Form to manage the data from the users table
 * @package Admindb
 * @subpackage FormmodelGenerated
 */
class UsersForm extends Sydney_Form
{
    public function __construct($options = null)
    {
        parent :: __construct($options);
        $this->setAttrib('accept-charset', 'UTF-8');
        $this->setName('users');

        $id = new Zend_Form_Element_Hidden('id');

        $hash = new Zend_Form_Element_Hash('no_csrf_foo', array('salt' => '4s564evzaSD64sf'));

        $submit = new Zend_Form_Element_Submit('submit');
        $submit->setAttrib('id', 'submitbutton');

        $login = new Zend_Form_Element_Text('login');
        $login->setLabel('login');

        $password = new Zend_Form_Element_Password('password');
        $password->setLabel('password');

        $usersGroupsId = new Zend_Form_Element_Select('usersgroups_id');
        $options = new Usersgroups();
        $usersGroupsId->addMultiOption('', '----------');
        foreach ($options->fetchAlltoFlatArray() as $k => $v) {
            $usersGroupsId->addMultiOption($k, $v['mlabel']);
        }

        $usersGroupsId->setLabel('usersgroups_id');

        $valid = new Zend_Form_Element_Checkbox('valid');
        $valid->setLabel('valid');

        $fileName = new Zend_Form_Element_Text('fname');
        $fileName->setLabel('fname');

        $mdName = new Zend_Form_Element_Text('mdname');
        $mdName->setLabel('mdname');

        $lastName = new Zend_Form_Element_Text('lname');
        $lastName->setLabel('lname');

        $phone = new Zend_Form_Element_Text('phone');
        $phone->setLabel('phone');

        $cell = new Zend_Form_Element_Text('cell');
        $cell->setLabel('cell');

        $email = new Zend_Form_Element_Text('email');
        $email->setLabel('email');

        $active = new Zend_Form_Element_Checkbox('active');
        $active->setLabel('active');

        $safinstancesId = new Zend_Form_Element_Select('safinstances_id');
        $options = new Safinstances();
        $safinstancesId->addMultiOption('', '----------');
        foreach ($options->fetchAlltoFlatArray() as $k => $v) {
            $safinstancesId->addMultiOption($k, $v['mlabel']);
        }

        $safinstancesId->setLabel('safinstances_id');

        $subscribeDate = new Zend_Form_Element_Text('subscribedate');
        $subscribeDate->setLabel('subscribedate');

        $unsubscribeDate = new Zend_Form_Element_Text('unsubscribedate');
        $unsubscribeDate->setLabel('unsubscribedate');

        $modifiedDate = new Zend_Form_Element_Text('modifieddate');
        $modifiedDate->setLabel('modifieddate');

        $ip = new Zend_Form_Element_Text('ip');
        $ip->setLabel('ip');

        $creatorIdentity = new Zend_Form_Element_Text('creatoridentity');
        $creatorIdentity->setLabel('creatoridentity');

        $avatar = new Zend_Form_Element_Text('avatar');
        $avatar->setLabel('avatar');

        $pageOrder = new Zend_Form_Element_Text('pagorder');
        $pageOrder->setLabel('pagorder');

        $lastLoginDate = new Zend_Form_Element_Text('lastlogindate');
        $lastLoginDate->setLabel('lastlogindate');

        $lastStatusChange = new Zend_Form_Element_Text('laststatuschange');
        $lastStatusChange->setLabel('laststatuschange');

        $lastPwdChanges = new Zend_Form_Element_Text('lastpwdchanges');
        $lastPwdChanges->setLabel('lastpwdchanges');

        $timeValidityPassword = new Zend_Form_Element_Text('timeValidityPassword');
        $timeValidityPassword->setLabel('timeValidityPassword');

        $lastPwdHistory = new Zend_Form_Element_Text('lastpwdhistory');
        $lastPwdHistory->setLabel('lastpwdhistory');

        $filFoldersUsers = new FilfolderslistForm('FilfoldersUsers');
        $filFoldersUsers->setLabel('FilfoldersUsers');
        $safinstancesUsers = new SafinstanceslistForm('SafinstancesUsers');
        $safinstancesUsers->setLabel('SafinstancesUsers');

        $this->addElements(array(
            $id,
            $hash,
            $login,
            $password,
            $usersGroupsId,
            $valid,
            $fileName,
            $mdName,
            $lastName,
            $phone,
            $cell,
            $email,
            $active,
            $safinstancesId,
            $subscribeDate,
            $unsubscribeDate,
            $modifiedDate,
            $ip,
            $creatorIdentity,
            $avatar,
            $pageOrder,
            $lastLoginDate,
            $lastStatusChange,
            $lastPwdChanges,
            $timeValidityPassword,
            $lastPwdHistory,
            $filFoldersUsers,
            $safinstancesUsers
        ));
        $this->addElements(array($submit));
    }

}
