<?php

/**
 *
 */
$paramArray = $this->allParams;
/**
 *
 * @param $params   array('lfrom' => 10)
 * @return string
 */
function _buildUrl($paramArray = array(), $params = array(), $paramToRemove = array())
{

    $excludedParams = array(
        'sydneylayout',
    );

    $excludedParams = array_merge($excludedParams, $paramToRemove);

    $ctrl = array('publicms', 'file', 'filelist');
    if (isset($paramArray['module']) &&
        isset($paramArray['controller']) &&
        isset($paramArray['action'])
    ) {
        $ctrl = array(
            $paramArray['module'],
            $paramArray['controller'],
            $paramArray['action']
        );
    }
    $furl = '/' . $ctrl[0] . '/' . $ctrl[1] . '/' . $ctrl[2] . '/';
    // $furl = '/publicms/index/view/';
    foreach ($params as $k => $v) {
        $paramArray[$k] = $v;
    }
    foreach ($paramArray as $k => $v) {
        if ($k == '_pageid') {
            // $furl .= 'page/'.$v.'/';
        } else if (!in_array($k, $excludedParams)) {
            $furl .= $k . '/' . $v . '/';
        }
    }

    return $furl;
}

if ($paramArray['uselightbox']) {
    ?>
    <script type="text/javascript"
            src="/jslibs/jquery/plugins/lightbox/js/jquery.lightbox-0.5.js"></script>
    <link rel="stylesheet" type="text/css"
          href="/jslibs/jquery/plugins/lightbox/css/jquery.lightbox-0.5.css"
          media="screen"/>
    <script type="text/javascript">
        $(function () {
            $('.gallerylight a.lighing').lightBox({ imageLoading: '/jslibs/jquery/plugins/lightbox/images/lightbox-ico-loading.gif',
                imageBtnPrev: '/jslibs/jquery/plugins/lightbox/images/lightbox-btn-prev.gif',
                imageBtnNext: '/jslibs/jquery/plugins/lightbox/images/lightbox-btn-next.gif',
                imageBtnClose: '/jslibs/jquery/plugins/lightbox/images/lightbox-btn-close.gif',
                imageBlank: '/jslibs/jquery/plugins/lightbox/images/lightbox-blank.gif' });
        });
    </script>
<?php } ?>

<?php
/**
 * Paginator calculation and definition
 */
$totalFiles = count($this->flist);
// JTO - 12/09/2013 - Correction du calcul, on calcul du bas (4,9 = 4) + 1 ==> 5 donc correct
// avant: round(4.9) = 5 + 1 = 6 incorrect
$pages = floor($totalFiles / $paramArray['loffset']) + 1;
$curPage = ($paramArray['lfrom'] / $paramArray['loffset']) + 1;
$paginator = '';

if ($pages > 1) {
    $prevN = ($paramArray['lfrom'] - $paramArray['loffset']);
    if ($prevN < 0) {
        $prevN = 0;
    }
    $paginator .= '<div class="pagination"><ul>';
    // JTO - 12/09/2013 - Pas besoin d'afficher un précédent si on est sur la 1ere page
    $paginator .= ($curPage == 1) ? '' : '<li><a href="' . _buildUrl($paramArray, array('lfrom' => $prevN)) . '">' . Sydney_Tools_Localization::_('Prev') . '</a></li>';
    for ($i = 1; $i <= $pages; $i++) {
        $paginator .= '<li';
        if ($i == $curPage) {
            $paginator .= ' class="disabled"';
        }
        $paginator .= '><a href="' . _buildUrl($paramArray, array('lfrom' => (($i - 1) * $paramArray['loffset']))) . '">' . $i . '</a></li>';
    }
    $fromN = ($paramArray['lfrom'] + $paramArray['loffset']);
    if ($fromN >= $totalFiles) {
        $fromN = $paramArray['lfrom'];
    }
    // JTO - 12/09/2013 - Pas besoin d'afficher un suivant si on est sur la derniere page
    $paginator .= ($curPage == $pages) ? '' : '<li><a href="' . _buildUrl($paramArray, array('lfrom' => $fromN)) . '">' . Sydney_Tools_Localization::_('Next') . '</a></li>';
    $paginator .= '</ul></div>';
}
?>

<div class="row-fluid">
    <? if ($paramArray['searchtool']) { ?>
    <div class="span9"><? } ?>
        <?= $paginator ?>
        <? if ($paramArray['searchtool']) { ?></div><? } ?>
    <? if ($paramArray['searchtool']) { ?>
        <form action="#" class="form_search" method="post"
              onsubmit="window.location=('<?= _buildUrl($paramArray, array('lfrom' => 0), array('srchstr')) ?>?srchstr='+$('#appendedInputButtonsrchtx').val());return false;">
            <div class="span3" style="padding-top: 20px;">
                <div class="input-append galleryform">

                    <input id="appendedInputButtonsrchtx" type="text"
                           value="<?= $this->srchstr ?>">
                    <button class="btn" type="button"
                            onclick="window.location=('<?= _buildUrl($paramArray, array('lfrom' => 0), array('srchstr')) ?>?srchstr='+$('#appendedInputButtonsrchtx').val());">
                        <i class="icon-search"></i></button>

                </div>
            </div>
        </form>
    <? } ?>
</div>


<div class="gallerylight">
    <?

    for ($i = 0; $i < $totalFiles; $i++) {
        if ($i >= $paramArray['lfrom'] && $i < ($paramArray['lfrom'] + $paramArray['loffset'])) {
            $lastDiv = false;
            $t = ($i % $paramArray['nbrCols']) + 1;
            $f = $this->flist[$i];
            $fil = Sydney_Medias_Filetypesfactory::createfiletype($f['path'] . '/' . $f['filename']);
            $finfo = $fil->getFileinfo();
            ?>

            <? if ($t == 1) { ?><div class="row-fluid"><? } ?>
            <div class="span<?= (12 / $paramArray['nbrCols']) ?>">
                <article class="thumbnail">
                    <p style="font-weight: bold;"><?= Sydney_Tools_Localization::_($f['label']) ?></p>
                    <a class="lighing"
                       href="/publicms/file/showimg/id/<?php echo $f['id']; ?>/dw/<?= $paramArray['fullimgWidth'] ?>"
                       title="<?= $f['label'] ?>"><img
                            src="/publicms/file/showimg/id/<?php echo $f['id']; ?>/dw/<?= $paramArray['thumbWidth'] ?>"
                            width="<?= $paramArray['thumbWidth'] ?>"></a>

                    <div class="caption">
                        <? if ($paramArray['downloadable']) { ?><a
                            class="btn more" target="_blank"
                            href="/publicms/file/getrfile/id/<?php echo $f['id']; ?>/download/yes/"><?= Sydney_Tools_Localization::_('Download') ?></a>
                            <br/><? } ?>
                        <?= Sydney_Tools_Localization::_($f['desc']) ?>&nbsp;
                    </div>
                </article>
            </div>
            <? if ($t == $paramArray['nbrCols']) {
                $lastDiv = true; ?></div><? } ?>
        <?php
        }
    }
    if (!$lastDiv) {
        print '</div>';
    }
    ?>
</div>
<?= $paginator ?>
