<?php
/**
 * File generated by the Sydney_Admin_Generator
 */

/**
 * @package Admindb
 * @subpackage ModelGenerated
 */
class PagstructurePagdivsOp extends Sydney_Db_Table
{

    /**
     * Returns true if this div is found in several structure nodes
     *
     * @param string $pagstructure_id
     * @param string $pagdivsId
     * @return Boolean
     */
    public function isDivShared($pagdivsId = '')
    {
        $row = $this->fetchAll(" pagdivs_id = '$pagdivsId' ");
        if (count($row) > 1) {
            return true;
        } else {
            return false;
        }

    }

    /**
     * @param string $pagdivsId
     */
    public function getIDsOfStructureWhereShared($pagdivsId = '')
    {
        $ar = array();
        $row = $this->fetchAll(" pagdivs_id = '$pagdivsId' ");
        foreach ($row as $r) {
            $ar[] = (int) $r->pagstructure_id;
        }

        return $ar;
    }

    public function setPagdivsLinkedToSafe($id, array $data)
    {
        if (preg_match("/[0-9]{1,9}/", $id) && is_array($data)) {
            $where = $this->getAdapter()->quoteInto('pagdivs_id = ?', $id);
            foreach ($this->fetchAll($where) as $node) {
                if (!in_array($node->pagstructure_id, $data)) {
                    $sql1 = " pagstructure_id = '" . $node->pagstructure_id . "' AND pagdivs_id = '" . $id . "' ";
                    $this->delete($sql1);
                    print $sql1;
                }
            }

            foreach ($data as $v) {
                $rows = $this->fetchAll("pagdivs_id = '" . $id . "' AND pagstructure_id = '" . $v . "' ");
                print_r(count($rows));
                if (count($rows) == 0) {
                    $this->insert(array(
                        'pagdivs_id'      => $id,
                        'pagstructure_id' => $v
                    ));
                }
            }

        } else {
            return false;
        }
    }

}
