<?php
/**
 * pages_edit view
 * @package Adminpages
 * @subpackage View
 */
$isDeveloper = $this->isDeveloper;
$pagstructure_id = $this->pagstructure_id;
?>
<?php echo $this->helpBox('/adminhelp/index/index/section/pageedit'); ?>
<script>

    var pagstructureid = <?php echo $this->pagid; ?>;
    var emodule = "<?php echo $this->emodule; ?>";

    $(document).ready(function () {
        $(this).Antidot_Contenttabs();
    });
</script>
<style>
    .accessRightsFilteredDiv {
        border: 2px solid orange;
    }

    .isShared {
        border: 2px solid #008800;
    }
</style>
<div id="sharedialog"></div>
<div id="savebutton">
    <input class="button bigwbutton" type="button" value="Save order"/>
</div>
<div class="ceUILibrary" style="display: none;">
    <div class="addContent">
        <p class="items sydney_editor_p">
            <?php echo $this->EditorAddContentBar(); ?>
        </p>

        <p class="close sydney_editor_p"><a class="button sydney_editor_a"
                                            href="#">Close</a></p>
    </div>
    <div class="addHere">
        <span class="ghost sydney_editor_span"></span>
        <a class="sydney_editor_a" href="#" onclick="return false;">Add here</a>
    </div>
    <li class="blankitem sydney_editor_li">
        <?php echo $this->EditorActions(); ?>
        <div class="content"></div>
    </li>
    <?php
    // print the result of the helpers
    $tyDB = new Pagdivtypes();
    foreach ($tyDB->fetchAll('online = 1') as $e) {
        if (($e->developeronly == 1 && $isDeveloper) || $e->developeronly == 0) {
            $hlpr = $e->helperadmin;
            // echo '<!-- Helper '.$e->label.' -->'."\n";
            echo $this->$hlpr();
        }
    }
    ?>
</div>
<div id="sydney_editor">
    <ul id="pageContent" class="contentEditor sydney_editor_ul"
        pagstructureid="<?= $pagstructure_id ?>">

        <?php
        /*
         * @change GDE - 08/05/2014 - Content Translation
         * Load translation
         */
        $this->contentTranslate = new Translate_Content_Content();

        foreach ($this->contentDivs as $div) {
            $coresp = new PagstructurePagdivs();
            $params = array('editLabel' => $div['label']);
            $isDeletable = true;
            $isDraft = false;
            $workflowEnabled = $div['workflowEnabled'];
            $isEditable = $div['isEditable'];
            $accessRightsEnabled = $div['accessRightsEnabled'];
            $msgNotEditable = $div['msgNotEditable'];
            $isShared = $coresp->isDivShared($div['pagdivs_id'], $div['pagstructure_id']);
            if ($isShared) {
                $sharedinids = Zend_Json::encode($coresp->getIDsOfStructureWhereShared($div['pagdivs_id']));
            }
            if ($sharedinids == '') {
                $sharedinids = "[" . $pagstructure_id . "]";
            }

            /*
             * @change GDE - 08/05/2014 - Content Translation
             * Get translation of content (from native table for default language and from translation table for others)
             */
            $div['content_draft'] = $this->contentTranslate->_($div['pagdivs_id'], $div['content_draft'], 'draft');
            $div['content'] = $this->contentTranslate->_($div['pagdivs_id'], $div['content']);

            if (!empty($div['content_draft'])) {
                $isDraft = true;
                if (!empty($div['content'])) {
                    $isDeletable = false;
                }
                if ($div['params_draft'] != '') {
                    eval('$params =' . $div['params_draft'] . ';');
                }
                $content = $div['content_draft'];
                $params['addClass'] = 'draft';
            } else {
                if ($div['params'] != '') {
                    eval('$params =' . $div['params'] . ';');
                }
                $params['addClass'] = '';
                $content = $div['content'];
            }

            if ($isShared) {
                $params['addClass'] .= ' isShared';
            }
            if ($div['online']) {
                $params['addClass'] .= ' onlinediv';
            } else {
                $params['addClass'] .= ' offlinediv';
            }
            if ($div['accessRightsFiltered']) {
                $params['addClass'] .= ' accessRightsFilteredDiv';
            }


            $tabs = '';
            if ($isDraft) { // tab only when draft content
                $tabs = '
			<div class="tabs" id="tabs-' . $div['pagdivs_id'] . '">
			    <ul>
			        <li id="draft-' . $div['pagdivs_id'] . '" class="draft active"><a href="' . $div['pagdivs_id'] . '">Draft</a></li>
			        <li id="published-' . $div['pagdivs_id'] . '" class="published notactive"><a href="' . $div['pagdivs_id'] . '">Actual content</a></li>
			    </ul>
			</div>';
            }

            $paramsEditorAction = array(
                'dbid'  => $div['pagdivs_id'],
                'label' => ($div['label'] ? $div['label'] : $div['code'] . '-' . $div['pagdivs_id'])
            );
            echo $this->{$div['helper']}(
                $tabs . $this->EditorActions(
                    $isDeletable,
                    $isDraft,
                    $div['online'],
                    $workflowEnabled,
                    $isEditable,
                    $accessRightsEnabled,
                    $msgNotEditable,
                    $paramsEditorAction,
                    $isShared),
                $content,
                $div['pagdivs_id'],
                $div['order'],
                $params,
                $this->moduleName,
                $pagstructure_id,
                $sharedinids
            );
        }
        ?>
        <li class="addContentStatic">
            <?php echo $this->EditorAddContentBar(); ?>
        </li>
    </ul>

</div>