<?php
/**
 * File generated by the Sydney_Admin_Generator
 */

/**
 * Form to manage the data from the filfiles table
 * @package Admindb
 * @subpackage FormmodelGenerated
 */
class FilfilesForm extends Sydney_Form
{
    public function __construct($options = null)
    {
        parent :: __construct($options);
        $this->setAttrib('accept-charset', 'UTF-8');
        $this->setName('filfiles');

        $id = new Zend_Form_Element_Hidden('id');

        $hash = new Zend_Form_Element_Hash('no_csrf_foo', array('salt' => '4s564evzaSD64sf'));

        $submit = new Zend_Form_Element_Submit('submit');
        $submit->setAttrib('id', 'submitbutton');

        $label = new Zend_Form_Element_Textarea('label');
        $label->setLabel('label');

        $desc = new Zend_Form_Element_Text('desc');
        $desc->setLabel('desc');

        $keywords = new Zend_Form_Element_Textarea('keywords');
        $keywords->setLabel('keywords');

        $fileName = new Zend_Form_Element_Textarea('filename');
        $fileName->setLabel('filename');

        $path = new Zend_Form_Element_Textarea('path');
        $path->setLabel('path');

        $type = new Zend_Form_Element_Text('type');
        $type->setLabel('type');

        $fileWeight = new Zend_Form_Element_Text('fweight');
        $fileWeight->setLabel('fweight');

        $imgWidth = new Zend_Form_Element_Text('imgwidth');
        $imgWidth->setLabel('imgwidth');

        $imgHeight = new Zend_Form_Element_Text('imgheight');
        $imgHeight->setLabel('imgheight');

        $techData = new Zend_Form_Element_Textarea('techdata');
        $techData->setLabel('techdata');

        $fileTypeId = new Zend_Form_Element_Select('filtype_id');
        $options = new Filtype();
        $fileTypeId->addMultiOption('', '----------');
        foreach ($options->fetchAlltoFlatArray() as $k => $v) {
            $fileTypeId->addMultiOption($k, $v['mlabel']);
        }

        $fileTypeId->setLabel('filtype_id');

        $usersId = new Zend_Form_Element_Select('users_id');
        $options = new Users();
        $usersId->addMultiOption('', '----------');
        foreach ($options->fetchAlltoFlatArray() as $k => $v) {
            $usersId->addMultiOption($k, $v['mlabel']);
        }

        $usersId->setLabel('users_id');

        $safinstancesId = new Zend_Form_Element_Select('safinstances_id');
        $options = new Safinstances();
        $safinstancesId->addMultiOption('', '----------');
        foreach ($options->fetchAlltoFlatArray() as $k => $v) {
            $safinstancesId->addMultiOption($k, $v['mlabel']);
        }

        $safinstancesId->setLabel('safinstances_id');

        $datecreated = new Zend_Form_Element_Text('datecreated');
        $datecreated->setLabel('datecreated');

        $datemodified = new Zend_Form_Element_Text('datemodified');
        $datemodified->setLabel('datemodified');

        $istagged = new Zend_Form_Element_Text('istagged');
        $istagged->setLabel('istagged');

        $idxcontent = new Zend_Form_Element_Text('idxcontent');
        $idxcontent->setLabel('idxcontent');

        $fileFilesFileMetaData = new FilmetadatalistForm('FilfilesFilmetadata');
        $fileFilesFileMetaData->setLabel('FilfilesFilmetadata');
        $fileFoldersFilefiles = new FilfolderslistForm('FilfoldersFilfiles');
        $fileFoldersFilefiles->setLabel('FilfoldersFilfiles');

        $this->addElements(array(
            $id,
            $hash,
            $label,
            $desc,
            $keywords,
            $fileName,
            $path,
            $type,
            $fileWeight,
            $imgWidth,
            $imgHeight,
            $techData,
            $fileTypeId,
            $usersId,
            $safinstancesId,
            $datecreated,
            $datemodified,
            $istagged,
            $idxcontent,
            $fileFilesFileMetaData,
            $fileFoldersFilefiles
        ));
        $this->addElements(array($submit));
    }

}
