<?php
/**
 * File generated by the Sydney_Admin_Generator
 */

/**
 * Form to manage the data from the filfolders table
 * @package Admindb
 * @subpackage FormmodelGenerated
 */
class FilfoldersFormOp extends Sydney_Form
{
    public function __construct($options = null)
    {
        parent :: __construct($options);
        $this->setAttrib('accept-charset', 'UTF-8');
        $this->setName('filfolders');

        $id = new Zend_Form_Element_Hidden('id');

        $hash = new Zend_Form_Element_Hash('no_csrf_foo', array('salt' => '4s564evzaSD64sf'));

        $submit = new Zend_Form_Element_Submit('submit');
        $submit->setAttrib('id', 'submitbutton');

        $label = new Zend_Form_Element_Text('label');
        $label->setLabel('label');

        $desc = new Zend_Form_Element_Textarea('desc');
        $desc->setLabel('desc');

        $parentId = new Zend_Form_Element_Select('parent_id');
        $options = new Filfolders();
        $parentId->addMultiOption('', '----------');
        foreach ($options->fetchAlltoFlatArray() as $k => $v) {
            $parentId->addMultiOption($k, $v['mlabel']);
        }
        $parentId->setLabel('parent_id');

        $isnode = new Zend_Form_Element_Text('isnode');
        $isnode->setLabel('isnode');

        $isparam = new Zend_Form_Element_Text('isparam');
        $isparam->setLabel('isparam');

        $relevance = new Zend_Form_Element_Text('relevance');
        $relevance->setLabel('relevance');

        $pagorder = new Zend_Form_Element_Text('pagorder');
        $pagorder->setLabel('pagorder');

        $linkedto = new Zend_Form_Element_Textarea('linkedto');
        $linkedto->setLabel('linkedto');

        $isSystemFolder = new Zend_Form_Element_Text('isSystemFolder');
        $isSystemFolder->setLabel('isSystemFolder');

        $this->addElements(array(
            $id,
            $hash,
            $label,
            $desc,
            $parentId,
            $isnode,
            $isparam,
            $relevance,
            $pagorder,
            $linkedto,
            $isSystemFolder
        ));
        $this->addElements(array($submit));
    }

}
