<?php
/**
 * File generated by the Sydney_Admin_Generator on the Nov 29, 2009 3:35:41 PM by arnaud@antidot.ca
 */

/**
 * Form to manage the data from the filmetadatacategories table
 * @package Admindb
 * @subpackage FormmodelGenerated
 */
class FilmetadatacategoriesForm extends Sydney_Form
{
    public function __construct($options = null)
    {
        parent :: __construct($options);
        $this->setAttrib('accept-charset', 'UTF-8');
        $this->setName('filmetadatacategories');

        $id = new Zend_Form_Element_Hidden('id');

        $hash = new Zend_Form_Element_Hash('no_csrf_foo', array('salt' => '4s564evzaSD64sf'));

        $submit = new Zend_Form_Element_Submit('submit');
        $submit->setAttrib('id', 'submitbutton');

        $label = new Zend_Form_Element_Text('label');
        $label->setLabel('label');

        $desc = new Zend_Form_Element_Textarea('desc');
        $desc->setLabel('desc');

        $this->addElements(array($id, $hash, $label, $desc));
        $this->addElements(array($submit));
    }

}
