<?php
/**
 * File generated by the Sydney_Admin_Generator v2.0
 */

/**
 * Mapping of the Applog table in an object
 * @package Admindb
 * @subpackage ModelGenerated
 */
class Applog extends ApplogOp
{
    protected $_schema = 'sydney';
    protected $_name = 'applog';
    protected $_primary = 'id';

    public $fieldsNames = array(
        'id', // bigint()
        'timestamp', // datetime()
        'priorityName', // varchar(20)
        'priority', // int()
        'className', // varchar(50)
        'message', // varchar(255)
        'identity', // varchar(50)
        'HTTP_REFERER', // varchar(200)
        'REMOTE_ADDR', // varchar(50)
        'REQUEST_METHOD', // varchar(50)
        'REQUEST_TIME', // varchar(50)
        'mysqltimestamp', // timestamp()
    );

    protected $_metadata = array(
        'id'             => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "applog",
            'COLUMN_NAME'      => "id",
            'COLUMN_POSITION'  => 1,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => true,
            'PRIMARY_POSITION' => 1,
            'IDENTITY'         => true,
        ),
        'timestamp'      => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "applog",
            'COLUMN_NAME'      => "timestamp",
            'COLUMN_POSITION'  => 2,
            'DATA_TYPE'        => "datetime",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'priorityName'   => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "applog",
            'COLUMN_NAME'      => "priorityName",
            'COLUMN_POSITION'  => 3,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => true,
            'LENGTH'           => "20",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'priority'       => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "applog",
            'COLUMN_NAME'      => "priority",
            'COLUMN_POSITION'  => 4,
            'DATA_TYPE'        => "int",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'className'      => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "applog",
            'COLUMN_NAME'      => "className",
            'COLUMN_POSITION'  => 5,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "50",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'message'        => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "applog",
            'COLUMN_NAME'      => "message",
            'COLUMN_POSITION'  => 6,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "255",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'identity'       => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "applog",
            'COLUMN_NAME'      => "identity",
            'COLUMN_POSITION'  => 7,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => true,
            'LENGTH'           => "50",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'HTTP_REFERER'   => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "applog",
            'COLUMN_NAME'      => "HTTP_REFERER",
            'COLUMN_POSITION'  => 8,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "200",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'REMOTE_ADDR'    => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "applog",
            'COLUMN_NAME'      => "REMOTE_ADDR",
            'COLUMN_POSITION'  => 9,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "50",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'REQUEST_METHOD' => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "applog",
            'COLUMN_NAME'      => "REQUEST_METHOD",
            'COLUMN_POSITION'  => 10,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "50",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'REQUEST_TIME'   => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "applog",
            'COLUMN_NAME'      => "REQUEST_TIME",
            'COLUMN_POSITION'  => 11,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "50",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'mysqltimestamp' => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "applog",
            'COLUMN_NAME'      => "mysqltimestamp",
            'COLUMN_POSITION'  => 12,
            'DATA_TYPE'        => "timestamp",
            'DEFAULT'          => "CURRENT_TIMESTAMP",
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
    );

    public function __construct($id = 0)
    {
        $this->_schema = Sydney_Tools_Sydneyglobals::getConf()->db->params->dbname;
        parent::__construct($id);
    }

}
