<?php
/**
 * File generated by the Sydney_Admin_Generator v2.0
 */

/**
 * Mapping of the Languages table in an object
 * @package Admindb
 * @subpackage ModelGenerated
 */
class Languages extends LanguagesOp
{
    protected $_schema = 'sydney';
    protected $_name = 'languages';
    protected $_dependentTables = array('Companies', 'Safinstances');
    protected $_primary = 'id';

    public $fieldsNames = array(
        'id', // bigint()
        'label', // varchar(50)
        'isocode', // varchar(2)
        'active', // tinyint()
    );

    protected $_metadata = array(
        'id'      => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "languages",
            'COLUMN_NAME'      => "id",
            'COLUMN_POSITION'  => 1,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => true,
            'PRIMARY_POSITION' => 1,
            'IDENTITY'         => true,
        ),
        'label'   => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "languages",
            'COLUMN_NAME'      => "label",
            'COLUMN_POSITION'  => 2,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => "",
            'NULLABLE'         => false,
            'LENGTH'           => "50",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'isocode' => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "languages",
            'COLUMN_NAME'      => "isocode",
            'COLUMN_POSITION'  => 3,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => "",
            'NULLABLE'         => false,
            'LENGTH'           => "2",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'active'  => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "languages",
            'COLUMN_NAME'      => "active",
            'COLUMN_POSITION'  => 4,
            'DATA_TYPE'        => "tinyint",
            'DEFAULT'          => "1",
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
    );

    public function __construct($id = 0)
    {
        $this->_schema = Sydney_Tools_Sydneyglobals::getConf()->db->params->dbname;
        parent::__construct($id);
    }

}
