<?php
/**
 * File generated by the Sydney_Admin_Generator v2.0
 */

/**
 * Mapping of the Safactions table in an object
 * @package Admindb
 * @subpackage ModelGenerated
 */
class Safactions extends SafactionsOp
{
    protected $_schema = 'sydney';
    protected $_name = 'safactions';
    protected $_dependentTables = array();
    protected $_referenceMap = array(
        'Safcontrollers' => array(
            'columns'       => 'safcontrollers_id',
            'refTableClass' => 'Safcontrollers',
            'refColumns'    => 'id'
        ),
    );
    protected $_primary = 'id';

    public $fieldsNames = array(
        'id', // bigint()
        'label', // varchar(45)
        'name', // varchar(45)
        'description', // text()
        'safcontrollers_id', // bigint()
    );

    protected $_metadata = array(
        'id'                => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safactions",
            'COLUMN_NAME'      => "id",
            'COLUMN_POSITION'  => 1,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => true,
            'PRIMARY_POSITION' => 1,
            'IDENTITY'         => true,
        ),
        'label'             => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safactions",
            'COLUMN_NAME'      => "label",
            'COLUMN_POSITION'  => 2,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "45",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'name'              => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safactions",
            'COLUMN_NAME'      => "name",
            'COLUMN_POSITION'  => 3,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "45",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'description'       => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safactions",
            'COLUMN_NAME'      => "description",
            'COLUMN_POSITION'  => 4,
            'DATA_TYPE'        => "text",
            'DEFAULT'          => null,
            'NULLABLE'         => true,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'safcontrollers_id' => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safactions",
            'COLUMN_NAME'      => "safcontrollers_id",
            'COLUMN_POSITION'  => 5,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
    );

    public function __construct($id = 0)
    {
        $this->_schema = Sydney_Tools_Sydneyglobals::getConf()->db->params->dbname;
        parent::__construct($id);
    }

}
