<?php
/**
 * File generated by the Sydney_Admin_Generator v2.0
 */

/**
 * Mapping of the Safactivitylog table in an object
 * @package Admindb
 * @subpackage ModelGenerated
 */
class Safactivitylog extends SafactivitylogOp
{
    protected $_schema = 'sydney';
    protected $_name = 'safactivitylog';
    protected $_dependentTables = array('Safactivitylog');
    protected $_referenceMap = array(
        'Users'          => array(
            'columns'       => 'users_id',
            'refTableClass' => 'Users',
            'refColumns'    => 'id'
        ),
        'Safactivitylog' => array(
            'columns'       => 'safactivitylog_id',
            'refTableClass' => 'Safactivitylog',
            'refColumns'    => 'id'
        ),
        'Safinstances'   => array(
            'columns'       => 'safinstances_id',
            'refTableClass' => 'Safinstances',
            'refColumns'    => 'id'
        ),
    );
    protected $_primary = 'id';

    public $fieldsNames = array(
        'id', // bigint()
        'timestamp', // timestamp()
        'priorityName', // varchar(20)
        'priority', // int()
        'className', // varchar(50)
        'message', // varchar(255)
        'users_id', // bigint()
        'login', // varchar(50)
        'fname', // varchar(50)
        'lname', // varchar(50)
        'module', // varchar(50)
        'action', // varchar(50)
        'module_table', // varchar(255)
        'module_ids', // varchar(255)
        'parent_id', // bigint()
        'safinstances_id', // bigint()
    );

    protected $_metadata = array(
        'id'              => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safactivitylog",
            'COLUMN_NAME'      => "id",
            'COLUMN_POSITION'  => 1,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => true,
            'PRIMARY_POSITION' => 1,
            'IDENTITY'         => true,
        ),
        'timestamp'       => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safactivitylog",
            'COLUMN_NAME'      => "timestamp",
            'COLUMN_POSITION'  => 2,
            'DATA_TYPE'        => "timestamp",
            'DEFAULT'          => "CURRENT_TIMESTAMP",
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'priorityName'    => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safactivitylog",
            'COLUMN_NAME'      => "priorityName",
            'COLUMN_POSITION'  => 3,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "20",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'priority'        => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safactivitylog",
            'COLUMN_NAME'      => "priority",
            'COLUMN_POSITION'  => 4,
            'DATA_TYPE'        => "int",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'className'       => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safactivitylog",
            'COLUMN_NAME'      => "className",
            'COLUMN_POSITION'  => 5,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "50",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'message'         => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safactivitylog",
            'COLUMN_NAME'      => "message",
            'COLUMN_POSITION'  => 6,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "255",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'users_id'        => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safactivitylog",
            'COLUMN_NAME'      => "users_id",
            'COLUMN_POSITION'  => 7,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'login'           => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safactivitylog",
            'COLUMN_NAME'      => "login",
            'COLUMN_POSITION'  => 8,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "50",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'fname'           => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safactivitylog",
            'COLUMN_NAME'      => "fname",
            'COLUMN_POSITION'  => 9,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "50",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'lname'           => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safactivitylog",
            'COLUMN_NAME'      => "lname",
            'COLUMN_POSITION'  => 10,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "50",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'module'          => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safactivitylog",
            'COLUMN_NAME'      => "module",
            'COLUMN_POSITION'  => 11,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "50",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'action'          => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safactivitylog",
            'COLUMN_NAME'      => "action",
            'COLUMN_POSITION'  => 12,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "50",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'module_table'    => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safactivitylog",
            'COLUMN_NAME'      => "module_table",
            'COLUMN_POSITION'  => 13,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "255",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'module_ids'      => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safactivitylog",
            'COLUMN_NAME'      => "module_ids",
            'COLUMN_POSITION'  => 14,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "255",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'parent_id'       => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safactivitylog",
            'COLUMN_NAME'      => "parent_id",
            'COLUMN_POSITION'  => 15,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'safinstances_id' => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safactivitylog",
            'COLUMN_NAME'      => "safinstances_id",
            'COLUMN_POSITION'  => 16,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
    );

    public function __construct($id = 0)
    {
        $this->_schema = Sydney_Tools_Sydneyglobals::getConf()->db->params->dbname;
        parent::__construct($id);
    }

}
