<?php
/**
 * File generated by the Sydney_Admin_Generator v2.0
 */

/**
 * Mapping of the Safmodules table in an object
 * @package Admindb
 * @subpackage ModelGenerated
 */
class Safmodules extends SafmodulesOp
{
    protected $_schema = 'sydney';
    protected $_name = 'safmodules';
    protected $_dependentTables = array(
        'Aclfunctions',
        'Bugitems',
        'Pagdivtypes',
        'Parameters',
        'Safcontrollers',
        'SafinstancesSafmodules',
        'Safprices',
    );
    protected $_referenceMap = array(
        'Usersgroups'      => array(
            'columns'       => 'usersgroups_id',
            'refTableClass' => 'Usersgroups',
            'refColumns'    => 'id'
        ),
        'Filfolders'       => array(
            'columns'       => 'filfolders_id',
            'refTableClass' => 'Filfolders',
            'refColumns'    => 'id'
        ),
        'Safinstancestype' => array(
            'columns'       => 'safinstancestype_id',
            'refTableClass' => 'Safinstancestype',
            'refColumns'    => 'id'
        ),
    );
    protected $_primary = 'id';

    public $fieldsNames = array(
        'id', // bigint()
        'label', // varchar(50)
        'image', // varchar(150)
        'description', // varchar(255)
        'usersgroups_id', // bigint()
        'prefix', // varchar(3)
        'name', // varchar(50)
        'showintab', // tinyint()
        'istechnical', // tinyint()
        'order', // int()
        'isalwaysactive', // tinyint()
        'isapplication', // tinyint()
        'longdesc', // text()
        'filfolders_id', // bigint()
        'safinstancestype_id', // bigint()
    );

    protected $_metadata = array(
        'id'                  => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safmodules",
            'COLUMN_NAME'      => "id",
            'COLUMN_POSITION'  => 1,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => true,
            'PRIMARY_POSITION' => 1,
            'IDENTITY'         => true,
        ),
        'label'               => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safmodules",
            'COLUMN_NAME'      => "label",
            'COLUMN_POSITION'  => 2,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "50",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'image'               => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safmodules",
            'COLUMN_NAME'      => "image",
            'COLUMN_POSITION'  => 3,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "150",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'description'         => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safmodules",
            'COLUMN_NAME'      => "description",
            'COLUMN_POSITION'  => 4,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "255",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'usersgroups_id'      => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safmodules",
            'COLUMN_NAME'      => "usersgroups_id",
            'COLUMN_POSITION'  => 5,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'prefix'              => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safmodules",
            'COLUMN_NAME'      => "prefix",
            'COLUMN_POSITION'  => 6,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => true,
            'LENGTH'           => "3",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'name'                => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safmodules",
            'COLUMN_NAME'      => "name",
            'COLUMN_POSITION'  => 7,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "50",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'showintab'           => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safmodules",
            'COLUMN_NAME'      => "showintab",
            'COLUMN_POSITION'  => 8,
            'DATA_TYPE'        => "tinyint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'istechnical'         => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safmodules",
            'COLUMN_NAME'      => "istechnical",
            'COLUMN_POSITION'  => 9,
            'DATA_TYPE'        => "tinyint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'order'               => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safmodules",
            'COLUMN_NAME'      => "order",
            'COLUMN_POSITION'  => 10,
            'DATA_TYPE'        => "int",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'isalwaysactive'      => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safmodules",
            'COLUMN_NAME'      => "isalwaysactive",
            'COLUMN_POSITION'  => 11,
            'DATA_TYPE'        => "tinyint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'isapplication'       => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safmodules",
            'COLUMN_NAME'      => "isapplication",
            'COLUMN_POSITION'  => 12,
            'DATA_TYPE'        => "tinyint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'longdesc'            => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safmodules",
            'COLUMN_NAME'      => "longdesc",
            'COLUMN_POSITION'  => 13,
            'DATA_TYPE'        => "text",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'filfolders_id'       => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safmodules",
            'COLUMN_NAME'      => "filfolders_id",
            'COLUMN_POSITION'  => 14,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'safinstancestype_id' => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "safmodules",
            'COLUMN_NAME'      => "safinstancestype_id",
            'COLUMN_POSITION'  => 15,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => "1",
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
    );

    public function __construct($id = 0)
    {
        $this->_schema = Sydney_Tools_Sydneyglobals::getConf()->db->params->dbname;
        parent::__construct($id);
    }

}
