<?php
/**
 * File generated by the Sydney_Admin_Generator v2.0
 */

/**
 * Mapping of the TranslationData table in an object
 * @package Admindb
 * @subpackage ModelGenerated
 */
class TranslationData extends TranslationDataOp
{
    protected $_schema = 'sydney';
    protected $_name = 'translation_data';
    protected $_referenceMap = array(
        'Safinstances' => array(
            'columns'       => 'safinstances_id',
            'refTableClass' => 'Safinstances',
            'refColumns'    => 'id'
        ),
        'Tbl'          => array(
            'columns'       => 'tbl_id',
            'refTableClass' => 'Tbl',
            'refColumns'    => 'id'
        ),
    );
    protected $_primary = 'id';

    public $fieldsNames = array(
        'id', // int()
        'safinstances_id', // int()
        'tbl_name', // varchar(150)
        'tbl_id', // int()
        'tbl_field', // varchar(50)
        'code_language', // char(3)
        'label', // longtext()
    );

    protected $_metadata = array(
        'id'              => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "translation_data",
            'COLUMN_NAME'      => "id",
            'COLUMN_POSITION'  => 1,
            'DATA_TYPE'        => "int",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => true,
            'PRIMARY_POSITION' => 1,
            'IDENTITY'         => true,
        ),
        'safinstances_id' => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "translation_data",
            'COLUMN_NAME'      => "safinstances_id",
            'COLUMN_POSITION'  => 2,
            'DATA_TYPE'        => "int",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'tbl_name'        => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "translation_data",
            'COLUMN_NAME'      => "tbl_name",
            'COLUMN_POSITION'  => 3,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "150",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'tbl_id'          => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "translation_data",
            'COLUMN_NAME'      => "tbl_id",
            'COLUMN_POSITION'  => 4,
            'DATA_TYPE'        => "int",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'tbl_field'       => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "translation_data",
            'COLUMN_NAME'      => "tbl_field",
            'COLUMN_POSITION'  => 5,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "50",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'code_language'   => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "translation_data",
            'COLUMN_NAME'      => "code_language",
            'COLUMN_POSITION'  => 6,
            'DATA_TYPE'        => "char",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "3",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'label'           => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "translation_data",
            'COLUMN_NAME'      => "label",
            'COLUMN_POSITION'  => 7,
            'DATA_TYPE'        => "longtext",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
    );

    /**
     * Returns the list of IDs linked to a "Translation"
     *
     * @param Int $id ID of the data
     * @return Array list of IDs
     */
    public function getTranslationLinkedTo($id)
    {
        if (preg_match("/[0-9]{1,9}/", $id)) {
            $toreturn = array();
            $rows = $this->fetchAll($this->select()->where('data_id = ?', $id));
            foreach ($rows->toArray() as $v) {
                $toreturn[] = $v['translation_id'];
            }

            return $toreturn;
        } else {
            return array();
        }
    }

    /**
     * Sets the data linked to an id in the "Translation" table
     *
     * @param Int $id ID of the data
     * @param Array list of IDs
     * @return Boolean true if success and false if there were an error
     */
    public function setTranslationLinkedTo($id, array $data)
    {
        if (preg_match("/[0-9]{1,9}/", $id) && is_array($data)) {
            $where = $this->getAdapter()->quoteInto('translation_id = ?', $id);
            $this->delete($where);
            foreach ($data as $v) {
                $this->insert(array('translation_id' => $id, 'data_id' => $v));
            }
        } else {
            return false;
        }
    }

    /**
     * Returns the list of IDs linked to a "Data"
     *
     * @param Int $id ID of the translation
     * @return Array list of IDs
     */
    public function getDataLinkedTo($id)
    {
        if (preg_match("/[0-9]{1,9}/", $id)) {
            $toreturn = array();
            $rows = $this->fetchAll($this->select()->where('translation_id = ?', $id));
            foreach ($rows->toArray() as $v) {
                $toreturn[] = $v['data_id'];
            }

            return $toreturn;
        } else {
            return array();
        }
    }

    /**
     * Sets the data linked to an id in the "Data" table
     *
     * @param Int $id ID of the translation
     * @param Array list of IDs
     * @return Boolean true if success and false if there were an error
     */
    public function setDataLinkedTo($id, array $data)
    {
        if (preg_match("/[0-9]{1,9}/", $id) && is_array($data)) {
            $where = $this->getAdapter()->quoteInto('data_id = ?', $id);
            $this->delete($where);
            foreach ($data as $v) {
                $this->insert(array('data_id' => $id, 'translation_id' => $v));
            }
        } else {
            return false;
        }
    }

    public function __construct($id = 0)
    {
        $this->_schema = Sydney_Tools_Sydneyglobals::getConf()->db->params->dbname;
        parent::__construct($id);
    }

}
