<?php

$translate = Zend_Registry::get('Zend_Translate');

$errors = $this->form->getDescription();
if ($errors) {
    ?>
    <div id="effortErrors" class="topError" style="display: block;">
        <ul>
            <li><?php echo $errors; ?></li>
        </ul>
    </div>
<?php
}
?>
<?php if ($this->showform) { ?>
    <p>
        <?php echo $translate->_('ifyoulostyourpassword'); ?>
    </p>
    <div id="flContent">
        <?php echo $this->form; ?>
    </div>
<?php } else { ?>
    <p>
        <?php echo $this->mmsg; ?>
    </p>
<?php } ?>
