<style>
    .filelistscroll {
        /*height: 390px;
        height: 590px;*/
        /* border: 1px solid #C5C5C5; */
        height: 360px;
        overflow: auto;
        /* background:#C5C5C5;*/
        /* padding:5px; */
    }

    #filesBrowse ul.filesGallery {
        height: 360px;
        overflow: auto;
        padding: 0 2px 0 4px;
    }

    #sitemap {
        height: 450px;
        overflow: auto;
    }

    .tree label {
        height: 15px;
        width: 450px;
    }

    .tree span.status {
        background: none;
    }

    #nodeContentObjects {
        background: none repeat scroll 0 0 #A1A1A1;
        overflow-y: auto;
        padding: 5px;
        z-index: 100;
        display: none;

        height: 200px;
        max-height: 250px;
        width: 200px;
        max-width: 250px;

        position: absolute;
        top: 77px;
        right: 21px;

        border: solid black 1px;
        border-right: 0;

        -moz-border-radius: 10px 0 0 10px;
        border-radius: 10px 0 0 10px;

    }

    #nodeContentObjects ul {
        display: block
    }

    #nodeContentObjects li {
        cursor: pointer;
        text-decoration: underline;
        font-size: 12px;
    }

    #nodeContentObjects li.liSelected {
        background: #CCCCCC;
    }

    #nodeContentObjects li.liTitle {
        cursor: default;
        font-weight: bold;
        font-size: 13px;
        text-decoration: none;
    }

</style>

<div id="nodeContentObjects"></div>
<hr/>

<div id="main" class="clearfix">

    <hr/>

    <div id="content" style="width:100%;max-height:450px;overflow-y:auto;">
        <div id="ajaxbox"></div>

        <div id="contentBrowser">
            <?php echo $this->StructureEditor($this->structureArray); ?>
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {
        var alreadyLoadedDisplayFiles = false;
        var selectedPageNode = 0;
        var selectedPageNodeObject = '';

        $(".dynatree-node").unbind('click')
            .unbind('mouseover')
            .unbind('mouseout');

        // Initialize the tree in the onload event
        $("#contentBrowser").dynatree({

            autoCollapse: false,
            persist: false,
            selectMode: 1,

            onActivate: function (node) {

                // remove selection from all nodes
                $(".dynatree-node").removeClass('itemselected');

                // select current node
                node.data.addClass = 'itemselected';
                selectedPageNode = node.data.key;

                // render
                node.render(true);

                // display object's node
                $('#nodeContentObjects').fadeOut('slow', function () {
                    $('#nodeContentObjects').html('Loading...Please wait...');
                    $.get('/adminpages/services/getlistpagdivs/?dbid=' + node.data.key, function (data) {
                        selectedPageNodeObject = '';
                        $('#nodeContentObjects').html(data);
                        if ($('#nodeContentObjects').is(':hidden')) {
                            $('#nodeContentObjects').show("slide", { direction: "right" }, 1000);
                        }

                        $('#nodeContentObjects li').not('.liTitle').click(function () {
                            if ($(this).hasClass('liSelected')) {
                                $('#nodeContentObjects li').removeClass('liSelected');
                                selectedPageNodeObject = '';
                            } else {
                                $('#nodeContentObjects li').removeClass('liSelected');
                                $(this).addClass('liSelected');
                                selectedPageNodeObject = $(this).attr('id');
                            }
                        });
                    });
                });

                return true;
            },
            onDeactivate: function (node) {
                node.data.addClass = '';
            },
            onExpand: null,
            dnd: null
        });

        $('#sitemap div.row').hover(function () {
            $(this).addClass('itemselected');

        }, function () {
            $(this).removeClass('itemselected');
        });

        $('#sitemap a').click(function () {
            return false;
        });

        $('#sitemap div.row').click(function () {
            if ($(this).hasClass('appear')) {
                $(this).removeClass('appear');
                selectedPageNode = 0;
            } else {
                $('#sitemap div.row').removeClass('appear');
                $(this).addClass('appear');

                var target_url = $('label > a', this).get(0).pathname;
                selectedPageNode = target_url.substr(target_url.lastIndexOf("/") + 1);
            }
        });

    });
</script>		
