
<table class="adminglobal">
    <thead>
    <tr>
        <th>Id</th>
        <th>Domain</th>
        <th>Label</th>
        <th>Creation date</th>
        <th>Action</th>
    </tr>
    </thead>
    <?php foreach($this->webinstances as $webinstance): ?>
        <tr>
            <td><?= $webinstance->id ;?></td>
            <td><?= $webinstance->domain ;?></td>
            <td><?= $webinstance->label ;?></td>
            <td><?= $webinstance->creationdate ;?></td>
            <td>
                <a class="button" href="/adminglobal/index/editsafinstances/id/<?= $webinstance->id ?>">Edit</a>
                <a class="button warning" href="/adminglobal/services/editsafinstances/format/json/id/<?= $webinstance->id ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach ?>
</table>

