<?php
$currentPage = $this->actionName;
?>
<div id="sidebar">
    <ul class="clearfix" id="localnav">
        <li>
            <?php if($currentPage == 'index'):?><strong><?php endif;?>
                <a href="/adminglobal/index/index">Dashboard</a>
            <?php if($currentPage == 'index'):?></strong><?php endif;?>
        </li>
        <li>
            <?php if($currentPage == 'usersgroups'):?><strong><?php endif;?>
                <a href="/adminglobal/index/usersgroups">Groups</a>
            <?php if($currentPage == 'usersgroups'):?></strong><?php endif;?>
        </li>
    </ul>
</div>