<?php
/**
 * File generated by the Sydney_Admin_Generator on the Feb 10, 2010 12:02:43 PM by arnaud@antidot.ca
 */

/**
 * Mapping of the Usersgroups table in an object
 * @package Admindb
 * @subpackage ModelGenerated
 */
class UsersgroupsOp extends Sydney_Db_Table
{
    /**
     * Returns an array of the parents
     * @param $id
     * @return array
     */
    public function getParentsIds($id)
    {
        $returnedIds = array($id);
        $currentId = $id;
        while ($currentId >= 1) {
            $parent = $this->fetchAll("id = '" . $currentId . "' ");
            $returnedIds[] = $parent->current()->parent_id;
            $currentId = $parent->current()->parent_id;
            if ($currentId == 1) {
                $currentId = 0;
            }
        }

        return $returnedIds;
    }

}
