<?php
/**
 * File generated by the Sydney_Admin_Generator v2.0
 */

/**
 * Mapping of the Filfolders table in an object
 * @package Admindb
 * @subpackage ModelGenerated
 */
class Filfolders extends FilfoldersOp
{
    protected $_schema = 'sydney';
    protected $_name = 'filfolders';
    protected $_dependentTables = array(
        'Filfolders',
        'FilfoldersFilfiles',
        'FilfoldersUsers',
        'Safmodules'
    );
    protected $_referenceMap = array(
        'Filfolders'   => array(
            'columns'       => 'filfolders_id',
            'refTableClass' => 'Filfolders',
            'refColumns'    => 'id'
        ),
        'Safinstances' => array(
            'columns'       => 'safinstances_id',
            'refTableClass' => 'Safinstances',
            'refColumns'    => 'id'
        ),
    );
    protected $_primary = 'id';

    public $fieldsNames = array(
        'id', // bigint()
        'label', // varchar(45)
        'desc', // varchar(255)
        'parent_id', // bigint()
        'safinstances_id', // bigint()
        'isnode', // tinyint()
        'isparam', // tinyint()
        'relevance', // int()
        'pagorder', // int()
        'linkedto', // varchar(150)
        'isSystemFolder', // smallint()
    );

    protected $_metadata = array(
        'id'              => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfolders",
            'COLUMN_NAME'      => "id",
            'COLUMN_POSITION'  => 1,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => true,
            'PRIMARY_POSITION' => 1,
            'IDENTITY'         => true,
        ),
        'label'           => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfolders",
            'COLUMN_NAME'      => "label",
            'COLUMN_POSITION'  => 2,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => true,
            'LENGTH'           => "45",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'desc'            => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfolders",
            'COLUMN_NAME'      => "desc",
            'COLUMN_POSITION'  => 3,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => true,
            'LENGTH'           => "255",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'parent_id'       => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfolders",
            'COLUMN_NAME'      => "parent_id",
            'COLUMN_POSITION'  => 4,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => true,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'safinstances_id' => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfolders",
            'COLUMN_NAME'      => "safinstances_id",
            'COLUMN_POSITION'  => 5,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'isnode'          => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfolders",
            'COLUMN_NAME'      => "isnode",
            'COLUMN_POSITION'  => 6,
            'DATA_TYPE'        => "tinyint",
            'DEFAULT'          => "0",
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'isparam'         => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfolders",
            'COLUMN_NAME'      => "isparam",
            'COLUMN_POSITION'  => 7,
            'DATA_TYPE'        => "tinyint",
            'DEFAULT'          => "0",
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'relevance'       => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfolders",
            'COLUMN_NAME'      => "relevance",
            'COLUMN_POSITION'  => 8,
            'DATA_TYPE'        => "int",
            'DEFAULT'          => "50",
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'pagorder'        => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfolders",
            'COLUMN_NAME'      => "pagorder",
            'COLUMN_POSITION'  => 9,
            'DATA_TYPE'        => "int",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'linkedto'        => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfolders",
            'COLUMN_NAME'      => "linkedto",
            'COLUMN_POSITION'  => 10,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => "0",
            'NULLABLE'         => false,
            'LENGTH'           => "150",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'isSystemFolder'  => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfolders",
            'COLUMN_NAME'      => "isSystemFolder",
            'COLUMN_POSITION'  => 11,
            'DATA_TYPE'        => "smallint",
            'DEFAULT'          => "0",
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
    );

    public function __construct($id = 0)
    {
        $this->_schema = Sydney_Tools_Sydneyglobals::getConf()->db->params->dbname;
        parent::__construct($id);
    }

}
