<?php
/**
 * File generated by the Sydney_Admin_Generator v2.0
 */

/**
 * Mapping of the FilfoldersUsers table in an object
 * @package Admindb
 * @subpackage ModelGenerated
 */
class FilfoldersUsers extends FilfoldersUsersOp
{
    protected $_schema = 'sydney';
    protected $_name = 'filfolders_users';
    protected $_referenceMap = array(
        'Filfolders' => array(
            'columns'       => 'filfolders_id',
            'refTableClass' => 'Filfolders',
            'refColumns'    => 'id'
        ),
        'Users'      => array(
            'columns'       => 'users_id',
            'refTableClass' => 'Users',
            'refColumns'    => 'id'
        ),
    );
    protected $_primary = 'id';

    public $fieldsNames = array(
        'filfolders_id', // bigint()
        'users_id', // bigint()
        'id', // bigint()
        'hits', // int()
        'isconfig', // tinyint()
        'love', // int()
        'like', // int()
        'bomb', // int()
    );

    protected $_metadata = array(
        'filfolders_id' => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfolders_users",
            'COLUMN_NAME'      => "filfolders_id",
            'COLUMN_POSITION'  => 1,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'users_id'      => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfolders_users",
            'COLUMN_NAME'      => "users_id",
            'COLUMN_POSITION'  => 2,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'id'            => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfolders_users",
            'COLUMN_NAME'      => "id",
            'COLUMN_POSITION'  => 3,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => true,
            'PRIMARY_POSITION' => 1,
            'IDENTITY'         => true,
        ),
        'hits'          => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfolders_users",
            'COLUMN_NAME'      => "hits",
            'COLUMN_POSITION'  => 4,
            'DATA_TYPE'        => "int",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'isconfig'      => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfolders_users",
            'COLUMN_NAME'      => "isconfig",
            'COLUMN_POSITION'  => 5,
            'DATA_TYPE'        => "tinyint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'love'          => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfolders_users",
            'COLUMN_NAME'      => "love",
            'COLUMN_POSITION'  => 6,
            'DATA_TYPE'        => "int",
            'DEFAULT'          => "0",
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'like'          => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfolders_users",
            'COLUMN_NAME'      => "like",
            'COLUMN_POSITION'  => 7,
            'DATA_TYPE'        => "int",
            'DEFAULT'          => "0",
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'bomb'          => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfolders_users",
            'COLUMN_NAME'      => "bomb",
            'COLUMN_POSITION'  => 8,
            'DATA_TYPE'        => "int",
            'DEFAULT'          => "0",
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
    );

    /**
     * Returns the list of IDs linked to a "Filfolders"
     *
     * @param Int $id ID of the users
     * @return Array list of IDs
     */
    public function getFilfoldersLinkedTo($id)
    {
        if (preg_match("/[0-9]{1,9}/", $id)) {
            $toreturn = array();
            $rows = $this->fetchAll($this->select()->where('users_id = ?', $id));
            foreach ($rows->toArray() as $v) {
                $toreturn[] = $v['filfolders_id'];
            }

            return $toreturn;
        } else {
            return array();
        }
    }

    /**
     * Sets the data linked to an id in the "Filfolders" table
     *
     * @param Int $id ID of the users
     * @param Array list of IDs
     * @return Boolean true if success and false if there were an error
     */
    public function setFilfoldersLinkedTo($id, array $data)
    {
        if (preg_match("/[0-9]{1,9}/", $id) && is_array($data)) {
            $where = $this->getAdapter()->quoteInto('filfolders_id = ?', $id);
            $this->delete($where);
            foreach ($data as $v) {
                $this->insert(array('filfolders_id' => $id, 'users_id' => $v));
            }
        } else {
            return false;
        }
    }

    /**
     * Returns the list of IDs linked to a "Users"
     *
     * @param Int $id ID of the filfolders
     * @return Array list of IDs
     */
    public function getUsersLinkedTo($id)
    {
        if (preg_match("/[0-9]{1,9}/", $id)) {
            $toreturn = array();
            $rows = $this->fetchAll($this->select()->where('filfolders_id = ?', $id));
            foreach ($rows->toArray() as $v) {
                $toreturn[] = $v['users_id'];
            }

            return $toreturn;
        } else {
            return array();
        }
    }

    /**
     * Sets the data linked to an id in the "Users" table
     *
     * @param Int $id ID of the filfolders
     * @param Array list of IDs
     * @return Boolean true if success and false if there were an error
     */
    public function setUsersLinkedTo($id, array $data)
    {
        if (preg_match("/[0-9]{1,9}/", $id) && is_array($data)) {
            $where = $this->getAdapter()->quoteInto('users_id = ?', $id);
            $this->delete($where);
            foreach ($data as $v) {
                $this->insert(array('users_id' => $id, 'filfolders_id' => $v));
            }
        } else {
            return false;
        }
    }

    public function __construct($id = 0)
    {
        $this->_schema = Sydney_Tools_Sydneyglobals::getConf()->db->params->dbname;
        parent::__construct($id);
    }

}
