<?php
/**
 * File generated by the Sydney_Admin_Generator v2.0
 */

/**
 * Mapping of the FilfilesFilmetadata table in an object
 * @package Admindb
 * @subpackage ModelGenerated
 */
class FilfilesFilmetadata extends FilfilesFilmetadataOp
{
    protected $_schema = 'sydney';
    protected $_name = 'filfiles_filmetadata';
    protected $_referenceMap = array(
        'Filmetadata' => array(
            'columns'       => 'filmetadata_id',
            'refTableClass' => 'Filmetadata',
            'refColumns'    => 'id'
        ),
        'Filfiles'    => array(
            'columns'       => 'filfiles_id',
            'refTableClass' => 'Filfiles',
            'refColumns'    => 'id'
        ),
    );
    protected $_primary = 'id';

    public $fieldsNames = array(
        'filmetadata_id', // bigint()
        'filfiles_id', // bigint()
        'id', // bigint()
        'value', // varchar(255)
    );

    protected $_metadata = array(
        'filmetadata_id' => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfiles_filmetadata",
            'COLUMN_NAME'      => "filmetadata_id",
            'COLUMN_POSITION'  => 1,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'filfiles_id'    => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfiles_filmetadata",
            'COLUMN_NAME'      => "filfiles_id",
            'COLUMN_POSITION'  => 2,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'id'             => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfiles_filmetadata",
            'COLUMN_NAME'      => "id",
            'COLUMN_POSITION'  => 3,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => true,
            'PRIMARY_POSITION' => 1,
            'IDENTITY'         => true,
        ),
        'value'          => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfiles_filmetadata",
            'COLUMN_NAME'      => "value",
            'COLUMN_POSITION'  => 4,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "255",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
    );

    /**
     * Returns the list of IDs linked to a "Filfiles"
     *
     * @param Int $id ID of the filmetadata
     * @return Array list of IDs
     */
    public function getFilfilesLinkedTo($id)
    {
        if (preg_match("/[0-9]{1,9}/", $id)) {
            $toreturn = array();
            $rows = $this->fetchAll($this->select()->where('filmetadata_id = ?', $id));
            foreach ($rows->toArray() as $v) {
                $toreturn[] = $v['filfiles_id'];
            }

            return $toreturn;
        } else {
            return array();
        }
    }

    /**
     * Sets the data linked to an id in the "Filfiles" table
     *
     * @param Int $id ID of the filmetadata
     * @param Array list of IDs
     * @return Boolean true if success and false if there were an error
     */
    public function setFilfilesLinkedTo($id, array $data)
    {
        if (preg_match("/[0-9]{1,9}/", $id) && is_array($data)) {
            $where = $this->getAdapter()->quoteInto('filfiles_id = ?', $id);
            $this->delete($where);
            foreach ($data as $v) {
                $this->insert(array(
                    'filfiles_id'    => $id,
                    'filmetadata_id' => $v
                ));
            }
        } else {
            return false;
        }
    }

    /**
     * Returns the list of IDs linked to a "Filmetadata"
     *
     * @param Int $id ID of the filfiles
     * @return Array list of IDs
     */
    public function getFilmetadataLinkedTo($id)
    {
        if (preg_match("/[0-9]{1,9}/", $id)) {
            $toreturn = array();
            $rows = $this->fetchAll($this->select()->where('filfiles_id = ?', $id));
            foreach ($rows->toArray() as $v) {
                $toreturn[] = $v['filmetadata_id'];
            }

            return $toreturn;
        } else {
            return array();
        }
    }

    /**
     * Sets the data linked to an id in the "Filmetadata" table
     *
     * @param Int $id ID of the filfiles
     * @param Array list of IDs
     * @return Boolean true if success and false if there were an error
     */
    public function setFilmetadataLinkedTo($id, array $data)
    {
        if (preg_match("/[0-9]{1,9}/", $id) && is_array($data)) {
            $where = $this->getAdapter()->quoteInto('filmetadata_id = ?', $id);
            $this->delete($where);
            foreach ($data as $v) {
                $this->insert(array(
                    'filmetadata_id' => $id,
                    'filfiles_id'    => $v
                ));
            }
        } else {
            return false;
        }
    }

    public function __construct($id = 0)
    {
        $this->_schema = Sydney_Tools_Sydneyglobals::getConf()->db->params->dbname;
        parent::__construct($id);
    }

}
