<?php
/**
 * File generated by the Sydney_Admin_Generator v2.0
 */

/**
 * Mapping of the Filfiles table in an object
 * @package Admindb
 * @subpackage ModelGenerated
 */
class Filfiles extends FilfilesOp
{
    protected $_schema = 'sydney';
    protected $_name = 'filfiles';
    protected $_dependentTables = array(
        'FilfilesFilmetadata',
        'FilfoldersFilfiles'
    );
    protected $_referenceMap = array(
        'Filtype'      => array(
            'columns'       => 'filtype_id',
            'refTableClass' => 'Filtype',
            'refColumns'    => 'id'
        ),
        'Users'        => array(
            'columns'       => 'users_id',
            'refTableClass' => 'Users',
            'refColumns'    => 'id'
        ),
        'Safinstances' => array(
            'columns'       => 'safinstances_id',
            'refTableClass' => 'Safinstances',
            'refColumns'    => 'id'
        ),
    );
    protected $_primary = 'id';

    public $fieldsNames = array(
        'id', // bigint()
        'label', // varchar(255)
        'desc', // text()
        'keywords', // varchar(255)
        'filename', // varchar(255)
        'type', // varchar(4)
        'fweight', // int()
        'imgwidth', // int()
        'imgheight', // int()
        'techdata', // varchar(255)
        'filtype_id', // bigint()
        'users_id', // bigint()
        'safinstances_id', // bigint()
        'datecreated', // datetime()
        'datemodified', // datetime()
        'istagged', // tinyint()
        'idxcontent', // text()
    );

    protected $_metadata = array(
        'id'              => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfiles",
            'COLUMN_NAME'      => "id",
            'COLUMN_POSITION'  => 1,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => true,
            'PRIMARY_POSITION' => 1,
            'IDENTITY'         => true,
        ),
        'label'           => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfiles",
            'COLUMN_NAME'      => "label",
            'COLUMN_POSITION'  => 2,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => true,
            'LENGTH'           => "255",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'desc'            => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfiles",
            'COLUMN_NAME'      => "desc",
            'COLUMN_POSITION'  => 3,
            'DATA_TYPE'        => "text",
            'DEFAULT'          => null,
            'NULLABLE'         => true,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'keywords'        => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfiles",
            'COLUMN_NAME'      => "keywords",
            'COLUMN_POSITION'  => 4,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => true,
            'LENGTH'           => "255",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'filename'        => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfiles",
            'COLUMN_NAME'      => "filename",
            'COLUMN_POSITION'  => 5,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "255",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'type'            => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfiles",
            'COLUMN_NAME'      => "type",
            'COLUMN_POSITION'  => 7,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => true,
            'LENGTH'           => "4",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'fweight'         => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfiles",
            'COLUMN_NAME'      => "fweight",
            'COLUMN_POSITION'  => 8,
            'DATA_TYPE'        => "int",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'imgwidth'        => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfiles",
            'COLUMN_NAME'      => "imgwidth",
            'COLUMN_POSITION'  => 9,
            'DATA_TYPE'        => "int",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'imgheight'       => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfiles",
            'COLUMN_NAME'      => "imgheight",
            'COLUMN_POSITION'  => 10,
            'DATA_TYPE'        => "int",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'techdata'        => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfiles",
            'COLUMN_NAME'      => "techdata",
            'COLUMN_POSITION'  => 11,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "255",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'filtype_id'      => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfiles",
            'COLUMN_NAME'      => "filtype_id",
            'COLUMN_POSITION'  => 12,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => true,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'users_id'        => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfiles",
            'COLUMN_NAME'      => "users_id",
            'COLUMN_POSITION'  => 13,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => true,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'safinstances_id' => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfiles",
            'COLUMN_NAME'      => "safinstances_id",
            'COLUMN_POSITION'  => 14,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => true,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'datecreated'     => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfiles",
            'COLUMN_NAME'      => "datecreated",
            'COLUMN_POSITION'  => 15,
            'DATA_TYPE'        => "datetime",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'datemodified'    => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfiles",
            'COLUMN_NAME'      => "datemodified",
            'COLUMN_POSITION'  => 16,
            'DATA_TYPE'        => "datetime",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'istagged'        => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfiles",
            'COLUMN_NAME'      => "istagged",
            'COLUMN_POSITION'  => 17,
            'DATA_TYPE'        => "tinyint",
            'DEFAULT'          => "0",
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'idxcontent'      => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filfiles",
            'COLUMN_NAME'      => "idxcontent",
            'COLUMN_POSITION'  => 18,
            'DATA_TYPE'        => "text",
            'DEFAULT'          => null,
            'NULLABLE'         => true,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
    );

    public function __construct($id = 0)
    {
        $this->_schema = Sydney_Tools_Sydneyglobals::getConf()->db->params->dbname;
        parent::__construct($id);
    }

}
