<?php
/**
 * File generated by the Sydney_Admin_Generator v2.0
 */

/**
 * Mapping of the Filmetadata table in an object
 * @package Admindb
 * @subpackage ModelGenerated
 */
class Filmetadata extends FilmetadataOp
{
    protected $_schema = 'sydney';
    protected $_name = 'filmetadata';
    protected $_dependentTables = array(
        'FilfilesFilmetadata',
        'Filmetadata',
        'FilmetadataFiltype'
    );
    protected $_referenceMap = array(
        'Safinstances' => array(
            'columns'       => 'safinstances_id',
            'refTableClass' => 'Safinstances',
            'refColumns'    => 'id'
        ),
        'Filmetadata'  => array(
            'columns'       => 'filmetadata_id',
            'refTableClass' => 'Filmetadata',
            'refColumns'    => 'id'
        ),
    );
    protected $_primary = 'id';

    public $fieldsNames = array(
        'id', // bigint()
        'label', // varchar(150)
        'desc', // varchar(255)
        'safinstances_id', // bigint()
        'parent_id', // bigint()
        'isnode', // tinyint()
        'editable', // tinyint()
    );

    protected $_metadata = array(
        'id'              => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filmetadata",
            'COLUMN_NAME'      => "id",
            'COLUMN_POSITION'  => 1,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => true,
            'PRIMARY_POSITION' => 1,
            'IDENTITY'         => true,
        ),
        'label'           => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filmetadata",
            'COLUMN_NAME'      => "label",
            'COLUMN_POSITION'  => 2,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "150",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'desc'            => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filmetadata",
            'COLUMN_NAME'      => "desc",
            'COLUMN_POSITION'  => 3,
            'DATA_TYPE'        => "varchar",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => "255",
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'safinstances_id' => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filmetadata",
            'COLUMN_NAME'      => "safinstances_id",
            'COLUMN_POSITION'  => 4,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'parent_id'       => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filmetadata",
            'COLUMN_NAME'      => "parent_id",
            'COLUMN_POSITION'  => 5,
            'DATA_TYPE'        => "bigint",
            'DEFAULT'          => null,
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'isnode'          => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filmetadata",
            'COLUMN_NAME'      => "isnode",
            'COLUMN_POSITION'  => 6,
            'DATA_TYPE'        => "tinyint",
            'DEFAULT'          => "0",
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
        'editable'        => array(
            'SCHEMA_NAME'      => null,
            'TABLE_NAME'       => "filmetadata",
            'COLUMN_NAME'      => "editable",
            'COLUMN_POSITION'  => 7,
            'DATA_TYPE'        => "tinyint",
            'DEFAULT'          => "1",
            'NULLABLE'         => false,
            'LENGTH'           => null,
            'SCALE'            => null,
            'PRECISION'        => null,
            'UNSIGNED'         => null,
            'PRIMARY'          => false,
            'PRIMARY_POSITION' => null,
            'IDENTITY'         => false,
        ),
    );

    public function __construct($id = 0)
    {
        $this->_schema = Sydney_Tools_Sydneyglobals::getConf()->db->params->dbname;
        parent::__construct($id);
    }

}
