<?php
//echo $this->docType('XHTML1_STRICT');

if (isset($this->layout()->avmodules[($this->layout()->currentModule)])) $mdn = $this->layout()->currentModule;
else $mdn = 'default';
$pprops = $this->layout()->avmodules[$mdn];


$trans = $this->layout()->translate;

echo '<?xml version="1.0" encoding="utf-8"?>'."\n\n";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="content-type"
		        content="application/xhtml+xml; charset=utf-8"/>
		<?php echo $this->headTitle(); ?>
		<script type="text/javascript">
			var sydneyadmin=true;
			var current_instance = <?php echo $this->safinstances_id; ?>;
			var applicationLanguage	= "<?php echo $settingsNms->ApplicationLanguage; ?>";
			var _ENV = "<?= Sydney_Tools_Sydneyglobals::getConf('general')->env ?>";
		</script>
		<?php echo $this->headStyle(); ?>
		<?php echo $this->headScript(); ?>
		<?php echo $this->headLink(); ?>

		<style>
			.filelistscroll	{
				/*height: 390px;
				height: 590px;*/
				/* border: 1px solid #C5C5C5; */
				height: 379px;
				/*overflow:auto;*/
				/* background:#C5C5C5;*/
				/* padding:5px; */
			}
			#filesBrowse ul.filesGallery {
				height: 379px;
				overflow:auto;
				padding:0 2px 0 4px;
			}

			#sitemap {
				height: 450px;
				overflow:auto;
			}

			.tree label {
				height: 15px;
				width:450px;
			}

			.tree span.status {
				background: none;
			}

			body {
				background: #E8E8E8 !important;
				padding: 0;
			}

			#content {
				background: #E8E8E8;
				margin-right: 0 !important;
				padding: 0 !important;
			}

			.clearfix {
				display: inline-block;
			}

			#main {
				background: none;
			}

			#nodeContentObjects {
			    background: none repeat scroll 0 0 #A1A1A1;
			    overflow-y: auto;
			    padding: 5px;
			    z-index:100;
			    display: none;

			    height: 200px;
			    max-height: 250px;
			    width: 200px;
			    max-width: 250px;

				position: fixed;
			    top: 77px;
			    right: 0;

				border: solid black 1px;
			    border-right: 0;

			    -moz-border-radius: 10px 0 0 10px;
			    border-radius: 10px 0 0 10px;

				-moz-box-shadow: 5px 5px 5px black;
				-webkit-box-shadow: 5px 5px 5px black;
				box-shadow: 5px 5px 5px black;

			}

			#nodeContentObjects ul {
				display: block
			}

			#nodeContentObjects li {
				cursor: pointer;
				text-decoration: underline;
				font-size: 12px;
			}

			#nodeContentObjects li.liSelected {
				background: #CCCCCC;
			}

			#nodeContentObjects li.liTitle {
				cursor: default;
				font-weight: bold;
				font-size: 13px;
				text-decoration: none;
			}

		</style>

		<script>

		function setUrl(url) {
			var currentDate = new Date();
			var editor		= window.opener.CKEDITOR.instances.editor1;
			var nodeUrl 	= $('.cke_dialog_ui_text label:visible:contains("URL")',window.opener.document).parent();
			var preview 	= $('img[id*="_previewImage"]',window.opener.document);

			// update url
			$('input',nodeUrl).val(url);
			// update preview
			$(preview).attr('src',url);
			$(preview).show();

			$('input',nodeUrl).focus();
		}

		$(document).ready(function() {
			var alreadyLoadedDisplayFiles = false;
			var selectedPageNode 		= 0;

			<?php if ($this->ckeditor_context == "image") {?>
				$('#sortBy2').val(1).change();
			<?php } elseif ($_GET['source'] == 'pagelink') {	?>
				$(".dynatree-node").unbind('click');
				$(".dynatree-node").unbind('mouseover');
				$(".dynatree-node").unbind('mouseout');

			    // Initialize the tree in the onload event
			    $("#viewcontent").dynatree({

					autoCollapse: false,
	    	        persist: false,
		    		selectMode: 1,

		    		onActivate: function(node) {

						// remove selection from all nodes
			        	$(".dynatree-node").removeClass('itemselected');

                        function sanitizeString(value) {

							var reg = new RegExp(" <div.*$", "g");
							value = value.replace(reg, '');

							var cleanedLabel = '';
							// JTO - On clean les labels des urls avec php pour garder la logique chez PHP
							$.ajax({
								dataType: "json",
								url: '/adminpages/services/getcleanlabelpage/',
								data: {label: value},
								async: false,
								success: function(data){
									cleanedLabel = data.cleanLabel;
								}
							});

							return cleanedLabel;
                        }

			        	// select current node
						node.data.addClass	= 'itemselected';
			        	selectedPageNode 	= node.data.key;
						$('#tempSelection').val(node.data.key);
                        var sanitizedTitle = sanitizeString(node.data.title);
                        $('#tempSelection').attr('data-label', sanitizedTitle);

			        	// render
			        	node.render(true);

						// display object's node
			        	$('#nodeContentObjects').fadeOut('slow',function () {
				        	$('#nodeContentObjects').html('Loading...Please wait...');
				        	$.get('/adminpages/services/getlistpagdivs/?dbid='+node.data.key, function(data) {
				        		$('#tempSelectionObject').val('');
				        		$('#nodeContentObjects').html(data);
				        		if ($('#nodeContentObjects').is(':hidden')) {
				        			$('#nodeContentObjects').show("slide", { direction: "right" }, 1000);
				        		}

				        		$('#nodeContentObjects li').not('.liTitle').click(function() {
					        		if ($(this).hasClass('liSelected')) {
					        			$('#nodeContentObjects li').removeClass('liSelected');
					        			$('#tempSelectionObject').val('');
					        		} else {
					        			$('#nodeContentObjects li').removeClass('liSelected');
					        			$(this).addClass('liSelected');
					        			$('#tempSelectionObject').val($(this).attr('id'));
					        		}
				        		});


				        	});
				        });

				        return true;
			        },
			        onDeactivate: function(node) {
			        	node.data.addClass	= '';
			        },
		    	    onExpand: null,
		    	    dnd: null
			    });
			<?php } ?>
		});
		</script>

	</head>
<body id="<?php echo $pprops[4]; ?>" class="cke_editor_editor1_dialog ">

<div id="nodeContentObjects"></div>

	<form>
		<input type="hidden" id="tempSelection" name="tempSelection" />
		<input type="hidden" id="tempSelectionObject" name="tempSelectionObject" />
	</form>
	<hr />
	<div id="main" class="clearfix">
		<div id="content" style="width:100%;">
			<div id="ajaxbox"></div>

		<div id="viewcontent">
		<?php echo $this->layout()->content; ?>
		</div>
		</div>
	</div>

</body>
</html>
