<!DOCTYPE html>
<html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
	<head>
        <meta charset="utf-8" />
		<title>Sydney::Login</title>
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headStyle(); ?>
		<?php echo $this->headScript(); ?>
		<?php echo $this->headLink(); ?>
	</head>

<body>

	<div id="sectionbar" class="login">
		<h1>Sydney administration</h1>
		<?php echo $this->layout()->content; ?>
	</div>
</body>
</html>
