<?php
/**
 * File generated by the Sydney_Admin_Generator
 */

/**
 * Form to manage the data from the applog table
 * @package Admindb
 * @subpackage FormmodelGenerated
 */
class ApplogForm extends Sydney_Form
{
    public function __construct($options = null)
    {
        parent :: __construct($options);
        $this->setAttrib('accept-charset', 'UTF-8');
        $this->setName('applog');

        $id = new Zend_Form_Element_Hidden('id');

        $hash = new Zend_Form_Element_Hash('no_csrf_foo', array('salt' => '4s564evzaSD64sf'));

        $submit = new Zend_Form_Element_Submit('submit');
        $submit->setAttrib('id', 'submitbutton');

        $timestamp = new Zend_Form_Element_Text('timestamp');
        $timestamp->setLabel('timestamp');

        $priorityName = new Zend_Form_Element_Text('priorityName');
        $priorityName->setLabel('priorityName');

        $priority = new Zend_Form_Element_Text('priority');
        $priority->setLabel('priority');

        $className = new Zend_Form_Element_Text('className');
        $className->setLabel('className');

        $message = new Zend_Form_Element_Textarea('message');
        $message->setLabel('message');

        $identity = new Zend_Form_Element_Text('identity');
        $identity->setLabel('identity');

        $httpReferer = new Zend_Form_Element_Textarea('HTTP_REFERER');
        $httpReferer->setLabel('HTTP_REFERER');

        $remoteAddr = new Zend_Form_Element_Text('REMOTE_ADDR');
        $remoteAddr->setLabel('REMOTE_ADDR');

        $requestMethod = new Zend_Form_Element_Text('REQUEST_METHOD');
        $requestMethod->setLabel('REQUEST_METHOD');

        $requestTime = new Zend_Form_Element_Text('REQUEST_TIME');
        $requestTime->setLabel('REQUEST_TIME');

        $mysqltimestamp = new Zend_Form_Element_Text('mysqltimestamp');
        $mysqltimestamp->setLabel('mysqltimestamp');

        $elements = array(
            $id,
            $hash,
            $timestamp,
            $priorityName,
            $priority,
            $className,
            $message,
            $identity,
            $httpReferer,
            $remoteAddr,
            $requestMethod,
            $requestTime,
            $mysqltimestamp
        );
        $this->addElements($elements);
        $this->addElements(array($submit));
    }

}
