<?php
/**
 * File generated by the Sydney_Admin_Generator
 */

/**
 * Form to manage the data from the safactivitylog table
 * @package Admindb
 * @subpackage FormmodelGenerated
 */
class SafactivitylogForm extends Sydney_Form
{
    public function __construct($options = null)
    {
        parent :: __construct($options);
        $this->setAttrib('accept-charset', 'UTF-8');
        $this->setName('safactivitylog');

        $id = new Zend_Form_Element_Hidden('id');

        $hash = new Zend_Form_Element_Hash('no_csrf_foo', array('salt' => '4s564evzaSD64sf'));

        $submit = new Zend_Form_Element_Submit('submit');
        $submit->setAttrib('id', 'submitbutton');

        $timestamp = new Zend_Form_Element_Text('timestamp');
        $timestamp->setLabel('timestamp');

        $priorityName = new Zend_Form_Element_Text('priorityName');
        $priorityName->setLabel('priorityName');

        $priority = new Zend_Form_Element_Text('priority');
        $priority->setLabel('priority');

        $className = new Zend_Form_Element_Text('className');
        $className->setLabel('className');

        $message = new Zend_Form_Element_Textarea('message');
        $message->setLabel('message');

        $usersId = new Zend_Form_Element_Select('users_id');
        $options = new Users();
        $usersId->addMultiOption('', '----------');
        foreach ($options->fetchAlltoFlatArray() as $k => $v) {
            $usersId->addMultiOption($k, $v['mlabel']);
        }

        $usersId->setLabel('users_id');

        $login = new Zend_Form_Element_Text('login');
        $login->setLabel('login');

        $fname = new Zend_Form_Element_Text('fname');
        $fname->setLabel('fname');

        $lname = new Zend_Form_Element_Text('lname');
        $lname->setLabel('lname');

        $module = new Zend_Form_Element_Text('module');
        $module->setLabel('module');

        $action = new Zend_Form_Element_Text('action');
        $action->setLabel('action');

        $moduleTable = new Zend_Form_Element_Textarea('module_table');
        $moduleTable->setLabel('module_table');

        $moduleIds = new Zend_Form_Element_Textarea('module_ids');
        $moduleIds->setLabel('module_ids');

        $parentId = new Zend_Form_Element_Select('parent_id');
        $options = new Safactivitylog();
        $parentId->addMultiOption('', '----------');
        foreach ($options->fetchAlltoFlatArray() as $k => $v) {
            $parentId->addMultiOption($k, $v['mlabel']);
        }

        $parentId->setLabel('parent_id');

        $safinstancesId = new Zend_Form_Element_Select('safinstances_id');
        $options = new Safinstances();
        $safinstancesId->addMultiOption('', '----------');
        foreach ($options->fetchAlltoFlatArray() as $k => $v) {
            $safinstancesId->addMultiOption($k, $v['mlabel']);
        }

        $safinstancesId->setLabel('safinstances_id');

        $this->addElements(array(
            $id,
            $hash,
            $timestamp,
            $priorityName,
            $priority,
            $className,
            $message,
            $usersId,
            $login,
            $fname,
            $lname,
            $module,
            $action,
            $moduleTable,
            $moduleIds,
            $parentId,
            $safinstancesId
        ));
        $this->addElements(array($submit));
    }

}
