<?php
/**
 * File generated by the Sydney_Admin_Generator
 */

/**
 * Form to manage the data from the safcontrollers table
 * @package Admindb
 * @subpackage FormmodelGenerated
 */
class SafcontrollersForm extends Sydney_Form
{
    public function __construct($options = null)
    {
        parent :: __construct($options);
        $this->setAttrib('accept-charset', 'UTF-8');
        $this->setName('safcontrollers');

        $id = new Zend_Form_Element_Hidden('id');

        $hash = new Zend_Form_Element_Hash('no_csrf_foo', array('salt' => '4s564evzaSD64sf'));

        $submit = new Zend_Form_Element_Submit('submit');
        $submit->setAttrib('id', 'submitbutton');

        $label = new Zend_Form_Element_Text('label');
        $label->setLabel('label');

        $name = new Zend_Form_Element_Text('name');
        $name->setLabel('name');

        $image = new Zend_Form_Element_Textarea('image');
        $image->setLabel('image');

        $description = new Zend_Form_Element_Textarea('description');
        $description->setLabel('description');

        $safmodulesId = new Zend_Form_Element_Select('safmodules_id');
        $options = new Safmodules();
        $safmodulesId->addMultiOption('', '----------');
        foreach ($options->fetchAlltoFlatArray() as $k => $v) {
            $safmodulesId->addMultiOption($k, $v['mlabel']);
        }

        $safmodulesId->setLabel('safmodules_id');

        $this->addElements(array(
            $id,
            $hash,
            $label,
            $name,
            $image,
            $description,
            $safmodulesId
        ));
        $this->addElements(array($submit));
    }

}
