<?php
/**
 * File generated by the Sydney_Admin_Generator
 */

/**
 * Sub form to manage the many to many links contained in the safcontrollers object
 */
class SafcontrollerslistForm extends Zend_Form_Element_MultiCheckbox
{
    public function init()
    {
        $options = new Safcontrollers();
        foreach ($options->fetchAlltoFlatArray() as $k => $v) {
            if (isset($v['mlabel'])) {
                $this->addMultiOption($k, $v['mlabel']);
            }
        }
    }
}
