<?php
/**
 * File generated by the Sydney_Admin_Generator
 */

/**
 * Form to manage the data from the safinstances table
 * @package Admindb
 * @subpackage FormmodelGenerated
 */
class SafinstancesForm extends Sydney_Form
{
    public function __construct($options = null)
    {
        parent :: __construct($options);
        $this->setAttrib('accept-charset', 'UTF-8');
        $this->setName('safinstances');

        $id = new Zend_Form_Element_Hidden('id');

        $hash = new Zend_Form_Element_Hash('no_csrf_foo', array('salt' => '4s564evzaSD64sf'));

        $submit = new Zend_Form_Element_Submit('submit');
        $submit->setAttrib('id', 'submitbutton');

        $label = new Zend_Form_Element_Text('label');
        $label->setLabel('label');

        $domain = new Zend_Form_Element_Text('domain');
        $domain->setLabel('domain');

        $description = new Zend_Form_Element_Textarea('description');
        $description->setLabel('description');

        $rootpath = new Zend_Form_Element_Text('rootpath');
        $rootpath->setLabel('rootpath');

        $languagesId = new Zend_Form_Element_Select('languages_id');
        $options = new Languages();
        $languagesId->addMultiOption('', '----------');
        foreach ($options->fetchAlltoFlatArray() as $k => $v) {
            $languagesId->addMultiOption($k, $v['mlabel']);
        }

        $languagesId->setLabel('languages_id');

        $database = new Zend_Form_Element_Text('database');
        $database->setLabel('database');

        $secdomains = new Zend_Form_Element_Text('secdomains');
        $secdomains->setLabel('secdomains');

        $creationdate = new Zend_Form_Element_Text('creationdate');
        $creationdate->setLabel('creationdate');

        $offlinedate = new Zend_Form_Element_Text('offlinedate');
        $offlinedate->setLabel('offlinedate');

        $active = new Zend_Form_Element_Checkbox('active');
        $active->setLabel('active');

        $offlinemessage = new Zend_Form_Element_Text('offlinemessage');
        $offlinemessage->setLabel('offlinemessage');

        $metatags = new Zend_Form_Element_Text('metakeywords');
        $metatags->setLabel('metakeywords');

        $pagMenusSafinstances = new PagmenuslistForm('PagmenusSafinstances');
        $pagMenusSafinstances->setLabel('PagmenusSafinstances');
        $safinstancesSafModules = new SafmoduleslistForm('SafinstancesSafmodules');
        $safinstancesSafModules->setLabel('SafinstancesSafmodules');
        $safinstancesUsers = new UserslistForm('SafinstancesUsers');
        $safinstancesUsers->setLabel('SafinstancesUsers');

        $this->addElements(array(
            $id,
            $hash,
            $label,
            $domain,
            $description,
            $rootpath,
            $languagesId,
            $database,
            $secdomains,
            $creationdate,
            $offlinedate,
            $active,
            $offlinemessage,
            $safinstancestypeId,
            $metatags,
            $pagMenusSafinstances,
            $safinstancesSafModules,
            $safinstancesUsers
        ));
        $this->addElements(array($submit));
    }

}
