<?php
/**
 * File generated by the Sydney_Admin_Generator
 */

/**
 * @package Admindb
 * @subpackage ModelGenerated
 */
class FilfoldersFilfilesOp extends Sydney_Db_Table
{

    /**
     *
     * @param $idFolder
     * @return Zend_Db_Table_Rowset_Abstract
     */
    public function getImageInfoByFolder($idFolder)
    {
        $select = $this->select()->setIntegrityCheck(false)
            ->from("filfiles")
            ->join(array("ff" => "filfolders_filfiles"), "filfiles.id = ff.filfiles_id")
            ->where('ff.filfolders_id = ?', $idFolder);

        return $this->fetchAll($select, Zend_DB::FETCH_ASSOC);
    }
}
