<?php
/**
 * index_create view
 * @package Adminpages
 * @subpackage View
 */

$n = null;
if ($this->parentid && !$this->node) {
} // echo 'add under this parentid';
else if ($this->parentid === null && !$this->node) {
} // echo 'add at the end';
else if ($this->node) {
    $n = $this->node; // edit mode
    $this->parentid = $n->parent_id;
}
?>
<?php echo $this->helpBox('/adminhelp/index/index/section/pageprops'); ?>
<script>
    $(function () {

        var lastValLabelUrl = ''; // Pour connaitre la derniere valeur du champs url
        if ($('input#url').length > 0) {

            /*
             Permet de gérer le cas si l'url est vide.
             Dans ce cas on autocomplete l'url en se basant sur
             le label de la page (titre de la page)
             */
            $('input#label').keyup(function () {
                // on met à jour l'url
                var $this = $(this),
                    value = $this.val();

                $.ajax({
                    dataType: "json",
                    url: '/adminpages/services/getcleanlabelpage/',
                    data: {label: value},
                    success: function (data) {
                        if (lastValLabelUrl == $('input#url').val() || $.trim($('input#url').val()) == '') {
                            $('input#url').val(data.cleanLabel);
                        }
                        lastValLabelUrl = data.cleanLabel;
                    }
                });

            });
            /**
             Lorsqu'on quitte le input de l'url
             on recalcule pour être sur qu'il n'y pas
             de caractères non autorisé
             */
            $('input#url').blur(function () {
                var $this = $(this),
                    value = $this.val();
                if ($.trim(value) == '') {
                    value = $.trim($('input#label').val());
                }
                $.ajax({
                    dataType: "json",
                    url: '/adminpages/services/getcleanlabelpage/',
                    data: {label: value},
                    success: function (data) {
                        $('input#url').val(data.cleanLabel);
                    }
                });
            });
        }
    });

</script>


<form action="/adminpages/index/editprocess" method="post" class="styled-form">

    <input type="hidden" name="id" value="<?php if ($n && $n->id) {
        echo $n->id;
    } ?>"/>

    <div class="form-group">
        <label
            for="label"> <?= Sydney_Tools_Localization::_('Page title') ?></label>

        <input type="text" id="label" name="label" class="form-control"
               value="<?php if ($n && $n->label) {
                   echo $this->escape($this->nodeTranslate->_($n->id, $n->label));
               } ?>"/>
        <span
            class="help-block"><?= Sydney_Tools_Localization::_('For example: About, Contact, ...') ?></span>
    </div>

    <div class="form-group">
        <label
            for="htmltitle"><?= Sydney_Tools_Localization::_('Page title tag') ?></label>

        <input type="text" id="htmltitle" name="htmltitle" class="form-control"
               value="<?php if ($n && $n->htmltitle) {
                   echo $this->escape($this->nodeTranslate->_($n->id, $n->htmltitle, 'htmltitle'));
               } ?>"/>
        <span
            class="help-block"><?= Sydney_Tools_Localization::_('About page title tag') ?></span>
    </div>

    <div class="form-group">
        <label for="url"><?= Sydney_Tools_Localization::_('Url') ?></label>

        http://<?= trim($_SERVER['HTTP_HOST'], '/') ?>/<input
            class="form-control input-inline" type="text"
            id="url" name="url"
            value="<?php if ($n && $n->url) {
                echo $this->escape($this->nodeTranslate->_($n->id, $n->url, 'url'));
            } ?>"/>
    </div>

    <div class="form-group">
        <label
            for="parentPage"><?= Sydney_Tools_Localization::_('Parent page') ?></label>

        <select id="parent_id" name="parent_id" class="form-control">
            <?php echo $this->StructureDropdown()->setStructureArray($this->structureArray)->setSelectedId($this->parentid); ?>
        </select>

        <span
            class="help-block"><?= Sydney_Tools_Localization::_('The main category for this page.') ?></span>
    </div>

    <div class="form-group">
        <label class="checkbox-inline" for="ishome">
            <input type="checkbox" id="ishome" name="ishome"
                   value="1" <?php if ($n && $n->ishome && $n->ishome == 1) {
                echo 'checked';
            } ?>/>
            <?= Sydney_Tools_Localization::_('Set this page as website') ?> <?= Sydney_Tools_Localization::_('Homepage') ?>
        </label>
    </div>


    <div class="form-group">
        <label
            for="usersgroups_id"><?= Sydney_Tools_Localization::_('Access rights') ?></label>

        <select id="usersgroups_id" name="usersgroups_id" class="form-control">
            <?php foreach ($this->usersgroups as $k => $usrg): ?>
                <option
                    value="<?php echo $k; ?>" <?php if ($n && $n->usersgroups_id && $n->usersgroups_id == $k) {
                    echo "selected";
                } ?> ><?php echo $usrg; ?></option>
            <?php endforeach; ?>
        </select>
        <span
            class="help-block"><?= Sydney_Tools_Localization::_('The group of users which could access this page and its children.') ?></span>
    </div>


    <div class="buttonsbox">
        <input type="submit" name="createPage"
               value="<?= Sydney_Tools_Localization::_('Save properties') ?>"/>
        <?= Sydney_Tools_Localization::_('or') ?> <a
            href="/adminpages"><?= Sydney_Tools_Localization::_('Cancel') ?></a>
    </div>

</form>